INSERT INTO verses (id, number, text, chapter_id) VALUES (30542, 1, "O que era desde o princípio, o que ouvimos, o que vimos com os nossos olhos, o que contemplamos e as nossas mãos apalparam — isto proclamamos a respeito da Palavra da vida.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30543, 2, "A vida se manifestou; nós a vimos e dela testemunhamos, e proclamamos a vocês a vida eterna, que estava com o Pai e nos foi manifestada.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30544, 3, "Nós lhes proclamamos o que vimos e ouvimos para que vocês também tenham comunhão conosco. Nossa comunhão é com o Pai e com seu Filho Jesus Cristo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30545, 4, "Escrevemos estas coisas para que a nossa alegria seja completa.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30546, 5, "Esta é a mensagem que dele ouvimos e transmitimos a vocês: Deus é luz; nele não há treva alguma.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30547, 6, "Se afirmarmos que temos comunhão com ele, mas andamos nas trevas, mentimos e não praticamos a verdade.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30548, 7, "Se, porém, andamos na luz, como ele está na luz, temos comunhão uns com os outros, e o sangue de Jesus, seu Filho, nos purifica de todo pecado.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30549, 8, "Se afirmarmos que estamos sem pecado, enganamo-nos a nós mesmos, e a verdade não está em nós.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30550, 9, "Se confessarmos os nossos pecados, ele é fiel e justo para perdoar os nossos pecados e nos purificar de toda injustiça.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30551, 10, "Se afirmarmos que não temos cometido pecado, fazemos de Deus um mentiroso, e a sua palavra não está em nós.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30552, 1, "Meus filhinhos, escrevo-lhes estas coisas para que vocês não pequem. Se, porém, alguém pecar, temos um intercessor junto ao Pai, Jesus Cristo, o Justo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30553, 2, "Ele é a propiciação pelos nossos pecados, e não somente pelos nossos, mas também pelos pecados de todo o mundo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30554, 3, "Sabemos que o conhecemos, se obedecemos aos seus mandamentos.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30555, 4, "Aquele que diz: ""Eu o conheço"", mas não obedece aos seus mandamentos, é mentiroso, e a verdade não está nele.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30556, 5, "Mas, se alguém obedece à sua palavra, nele verdadeiramente o amor de Deus está aperfeiçoado. Desta forma sabemos que estamos nele:", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30557, 6, "aquele que afirma que permanece nele, deve andar como ele andou.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30558, 7, "Amados, não lhes escrevo um mandamento novo, mas um mandamento antigo, que vocês têm desde o princípio: a mensagem que ouviram.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30559, 8, "No entanto, eu lhes escrevo um mandamento novo, o qual é verdadeiro nele e em vocês, pois as trevas estão se dissipando e já brilha a verdadeira luz.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30560, 9, "Quem afirma estar na luz mas odeia seu irmão, continua nas trevas.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30561, 10, "Quem ama seu irmão permanece na luz, e nele não há causa de tropeço.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30562, 11, "Mas quem odeia seu irmão está nas trevas e anda nas trevas; não sabe para onde vai, porque as trevas o cegaram.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30563, 12, "Filhinhos, eu lhes escrevo porque os seus pecados foram perdoados, graças ao nome de Jesus.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30564, 13, "Pais, eu lhes escrevo porque vocês conhecem aquele que é desde o princípio. Jovens, eu lhes escrevo porque venceram o Maligno.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30565, 14, "Filhinhos, eu lhes escrevi porque vocês conhecem o Pai. Pais, eu lhes escrevi porque vocês conhecem aquele que é desde o princípio. Jovens, eu lhes escrevi, porque vocês são fortes, e em vocês a Palavra de Deus permanece e vocês venceram o Maligno.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30566, 15, "Não amem o mundo nem o que nele há. Se alguém amar o mundo, o amor do Pai não está nele.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30567, 16, "Pois tudo o que há no mundo — a cobiça da carne, a cobiça dos olhos e a ostentação dos bens — não provém do Pai, mas do mundo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30568, 17, "O mundo e a sua cobiça passam, mas aquele que faz a vontade de Deus permanece para sempre.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30569, 18, "Filhinhos, esta é a última hora; e, assim como vocês ouviram que o anticristo está vindo, já agora muitos anticristos têm surgido. Por isso sabemos que esta é a última hora.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30570, 19, "Eles saíram do nosso meio, mas na realidade não eram dos nossos, pois, se fossem dos nossos, teriam permanecido conosco; o fato de terem saído mostra que nenhum deles era dos nossos.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30571, 20, "Mas vocês têm uma unção que procede do Santo, e todos vocês têm conhecimento.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30572, 21, "Não lhes escrevo porque não conhecem a verdade, mas porque vocês a conhecem e porque nenhuma mentira procede da verdade.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30573, 22, "Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Este é o anticristo: aquele que nega o Pai e o Filho.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30574, 23, "Todo o que nega o Filho também não tem o Pai; quem confessa publicamente o Filho tem também o Pai.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30575, 24, "Quanto a vocês, cuidem para que aquilo que ouviram desde o princípio permaneça em vocês. Se o que ouviram desde o princípio permanecer em vocês, vocês também permanecerão no Filho e no Pai.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30576, 25, "E esta é a promessa que ele nos fez: a vida eterna.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30577, 26, "Escrevo-lhes estas coisas a respeito daqueles que os querem enganar.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30578, 27, "Quanto a vocês, a unção que receberam dele permanece em vocês, e não precisam que alguém os ensine; mas, como a unção dele recebida, que é verdadeira e não falsa, os ensina acerca de todas as coisas, permaneçam nele como ele os ensinou.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30579, 28, "Filhinhos, agora permaneçam nele para que, quando ele se manifestar, tenhamos confiança e não sejamos envergonhados diante dele na sua vinda.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30580, 29, "Se vocês sabem que ele é justo, saibam também que todo aquele que pratica a justiça é nascido dele.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30581, 1, "Vejam como é grande o amor que o Pai nos concedeu: que fôssemos chamados filhos de Deus, o que de fato somos! Por isso o mundo não nos conhece, porque não o conheceu.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30582, 2, "Amados, agora somos filhos de Deus, e ainda não se manifestou o que havemos de ser, mas sabemos que, quando ele se manifestar, seremos semelhantes a ele, pois o veremos como ele é.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30583, 3, "Todo aquele que nele tem esta esperança purifica-se a si mesmo, assim como ele é puro.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30584, 4, "Todo aquele que pratica o pecado transgride a Lei; de fato, o pecado é a transgressão da Lei.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30585, 5, "Vocês sabem que ele se manifestou para tirar os nossos pecados, e nele não há pecado.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30586, 6, "Todo aquele que nele permanece não está no pecado. Todo aquele que está no pecado não o viu nem o conheceu.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30587, 7, "Filhinhos, não deixem que ninguém os engane. Aquele que pratica a justiça é justo, assim como ele é justo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30588, 8, "Aquele que pratica o pecado é do diabo, porque o diabo vem pecando desde o princípio. Para isso o Filho de Deus se manifestou: para destruir as obras do diabo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30589, 9, "Todo aquele que é nascido de Deus não pratica o pecado, porque a semente de Deus permanece nele; ele não pode estar no pecado, porque é nascido de Deus.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30590, 10, "Desta forma sabemos quem são os filhos de Deus e quem são os filhos do diabo: quem não pratica a justiça não procede de Deus; e também quem não ama seu irmão.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30591, 11, "Esta é a mensagem que vocês ouviram desde o princípio: que nos amemos uns aos outros.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30592, 12, "Não sejamos como Caim, que pertencia ao Maligno e matou seu irmão. E por que o matou? Porque suas obras eram más e as de seu irmão eram justas.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30593, 13, "Meus irmãos, não se admirem se o mundo os odeia.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30594, 14, "Sabemos que já passamos da morte para a vida porque amamos nossos irmãos. Quem não ama permanece na morte.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30595, 15, "Quem odeia seu irmão é assassino, e vocês sabem que nenhum assassino tem vida eterna em si mesmo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30596, 16, "Nisto conhecemos o que é o amor: Jesus Cristo deu a sua vida por nós, e devemos dar a nossa vida por nossos irmãos.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30597, 17, "Se alguém tiver recursos materiais e, vendo seu irmão em necessidade, não se compadecer dele, como pode permanecer nele o amor de Deus?", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30598, 18, "Filhinhos, não amemos de palavra nem de boca, mas em ação e em verdade.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30599, 19, "Assim saberemos que somos da verdade; e tranqüilizaremos o nosso coração diante dele", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30600, 20, "quando o nosso coração nos condenar. Porque Deus é maior do que o nosso coração e sabe todas as coisas.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30601, 21, "Amados, se o nosso coração não nos condenar, temos confiança diante de Deus", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30602, 22, "e recebemos dele tudo o que pedimos, porque obedecemos aos seus mandamentos e fazemos o que lhe agrada.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30603, 23, "E este é o seu mandamento: que creiamos no nome de seu Filho Jesus Cristo e que nos amemos uns aos outros, como ele nos ordenou.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30604, 24, "Os que obedecem aos seus mandamentos permanecem nele, e ele neles. Deste modo sabemos que ele permanece em nós: pelo Espírito que nos deu.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30605, 1, "Amados, não creiam em qualquer espírito, mas examinem os espíritos para ver se eles procedem de Deus, porque muitos falsos profetas têm saído pelo mundo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30606, 2, "Vocês podem reconhecer o Espírito de Deus deste modo: todo espírito que confessa que Jesus Cristo veio em carne procede de Deus;", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30607, 3, "mas todo espírito que não confessa a Jesus não procede de Deus. Esse é o espírito do anticristo, acerca do qual vocês ouviram que está vindo, e agora já está no mundo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30608, 4, "Filhinhos, vocês são de Deus e os venceram, porque aquele que está em vocês é maior do que aquele que está no mundo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30609, 5, "Eles vêm do mundo. Por isso o que falam procede do mundo, e o mundo os ouve.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30610, 6, "Nós viemos de Deus, e todo aquele que conhece a Deus nos ouve; mas quem não vem de Deus não nos ouve. Dessa forma reconhecemos o Espírito da verdade e o espírito do erro.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30611, 7, "Amados, amemo-nos uns aos outros, pois o amor procede de Deus. Aquele que ama é nascido de Deus e conhece a Deus.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30612, 8, "Quem não ama não conhece a Deus, porque Deus é amor.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30613, 9, "Foi assim que Deus manifestou o seu amor entre nós: enviou o seu Filho Unigênito ao mundo, para que pudéssemos viver por meio dele.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30614, 10, "Nisto consiste o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou seu Filho como propiciação pelos nossos pecados.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30615, 11, "Amados, visto que Deus assim nos amou, nós também devemos amar-nos uns aos outros.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30616, 12, "Ninguém jamais viu a Deus; se nos amarmos uns aos outros, Deus permanece em nós, e o seu amor está aperfeiçoado em nós.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30617, 13, "Sabemos que permanecemos nele, e ele em nós, porque ele nos deu do seu Espírito.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30618, 14, "E vimos e testemunhamos que o Pai enviou seu Filho para ser o Salvador do mundo.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30619, 15, "Se alguém confessa publicamente que Jesus é o Filho de Deus, Deus permanece nele, e ele em Deus.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30620, 16, "Assim conhecemos o amor que Deus tem por nós e confiamos nesse amor. Deus é amor. Todo aquele que permanece no amor permanece em Deus, e Deus nele.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30621, 17, "Dessa forma o amor está aperfeiçoado entre nós, para que no dia do juízo tenhamos confiança, porque neste mundo somos como ele.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30622, 18, "No amor não há medo; pelo contrário o perfeito amor expulsa o medo, porque o medo supõe castigo. Aquele que tem medo não está aperfeiçoado no amor.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30623, 19, "Nós amamos porque ele nos amou primeiro.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30624, 20, "Se alguém afirmar: ""Eu amo a Deus"", mas odiar seu irmão, é mentiroso, pois quem não ama seu irmão, a quem vê, não pode amar a Deus, a quem não vê.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30625, 21, "Ele nos deu este mandamento: Quem ama a Deus, ame também seu irmão.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30626, 1, "Todo aquele que crê que Jesus é o Cristo é nascido de Deus, e todo aquele que ama o Pai ama também ao que dele foi gerado.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30627, 2, "Assim sabemos que amamos os filhos de Deus: amando a Deus e obedecendo aos seus mandamentos.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30628, 3, "Porque nisto consiste o amor a Deus: obedecer aos seus mandamentos. E os seus mandamentos não são pesados.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30629, 4, "O que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30630, 5, "Quem é que vence o mundo? Somente aquele que crê que Jesus é o Filho de Deus.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30631, 6, "Este é aquele que veio por meio de água e sangue, Jesus Cristo: não somente por água, mas por água e sangue. E o Espírito é quem dá testemunho, porque o Espírito é a verdade.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30632, 7, "Há três que dão testemunho:", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30633, 8, "o Espírito, a água e o sangue; e os três são unânimes.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30634, 9, "Nós aceitamos o testemunho dos homens, mas o testemunho de Deus tem maior valor, pois é o testemunho de Deus, que ele dá acerca de seu Filho.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30635, 10, "Quem crê no Filho de Deus tem em si mesmo esse testemunho. Quem não crê em Deus o faz mentiroso, porque não crê no testemunho que Deus dá acerca de seu Filho.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30636, 11, "E este é o testemunho: Deus nos deu a vida eterna, e essa vida está em seu Filho.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30637, 12, "Quem tem o Filho, tem a vida; quem não tem o Filho de Deus, não tem a vida.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30638, 13, "Escrevi-lhes estas coisas, a vocês que crêem no nome do Filho de Deus, para que vocês saibam que têm a vida eterna.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30639, 14, "Esta é a confiança que temos ao nos aproximarmos de Deus: se pedirmos alguma coisa de acordo com a sua vontade, ele nos ouve.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30640, 15, "E se sabemos que ele nos ouve em tudo o que pedimos, sabemos que temos o que dele pedimos.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30641, 16, "Se alguém vir seu irmão cometer pecado que não leva à morte, ore, e Deus lhe dará vida. Refiro-me àqueles cujo pecado não leva à morte. Há pecado que leva à morte; não estou dizendo que se deva orar por este.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30642, 17, "Toda injustiça é pecado, mas há pecado que não leva à morte.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30643, 18, "Sabemos que todo aquele que é nascido de Deus não está no pecado; aquele que nasceu de Deus o protege, e o Maligno não o atinge.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30644, 19, "Sabemos que somos de Deus e que o mundo todo está sob o poder do Maligno.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30645, 20, "Sabemos também que o Filho de Deus veio e nos deu entendimento, para que conheçamos aquele que é o Verdadeiro. E nós estamos naquele que é o Verdadeiro, em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.", 61);
INSERT INTO verses (id, number, text, chapter_id) VALUES (30646, 21, "Filhinhos, guardem-se dos ídolos.", 61);