INSERT INTO verses (id, number, text, chapter_id) VALUES (29698, 1, "Paulo, apóstolo de Cristo Jesus, por ordem de Deus, nosso Salvador, e de Cristo Jesus, a nossa esperança,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29699, 2, "a Timóteo, meu verdadeiro filho na fé: Graça, misericórdia e paz da parte de Deus Pai e de Cristo Jesus, o nosso Senhor.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29700, 3, "Partindo eu para a Macedônia, roguei-lhe que permanecesse em Éfeso para ordenar a certas pessoas que não mais ensinem doutrinas falsas,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29701, 4, "e que deixem de dar atenção a mitos e genealogias intermináveis, que causam controvérsias em vez de promoverem a obra de Deus, que é pela fé.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29702, 5, "O objetivo desta instrução é o amor que procede de um coração puro, de uma boa consciência e de uma fé sincera.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29703, 6, "Alguns se desviaram dessas coisas, voltando-se para discussões inúteis,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29704, 7, "querendo ser mestres da lei, quando não compreendem nem o que dizem nem as coisas acerca das quais fazem afirmações tão categóricas.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29705, 8, "Sabemos que a lei é boa, se alguém a usa de maneira adequada.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29706, 9, "Também sabemos que ela não é feita para os justos, mas para os transgressores e insubordinados, para os ímpios e pecadores, para os profanos e irreverentes, para os que matam pai e mãe, para os homicidas,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29707, 10, "para os que praticam imoralidade sexual e os homossexuais, para os seqüestradores, para os mentirosos e os que juram falsamente; e para todo aquele que se opõe à sã doutrina.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29708, 11, "Essa sã doutrina se vê no glorioso evangelho que me foi confiado, o evangelho do Deus bendito.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29709, 12, "Dou graças a Cristo Jesus, nosso Senhor, que me deu forças e me considerou fiel, designando-me para o ministério,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29710, 13, "a mim que anteriormente fui blasfemo, perseguidor e insolente; mas alcancei misericórdia, porque o fiz por ignorância e na minha incredulidade;", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29711, 14, "contudo, a graça de nosso Senhor transbordou sobre mim, juntamente com a fé e o amor que estão em Cristo Jesus.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29712, 15, "Esta afirmação é fiel e digna de toda aceitação: Cristo Jesus veio ao mundo para salvar os pecadores, dos quais eu sou o pior.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29713, 16, "Mas, por isso mesmo alcancei misericórdia, para que em mim, o pior dos pecadores, Cristo Jesus demonstrasse toda a grandeza da sua paciência, usando-me como um exemplo para aqueles que nele haveriam de crer para a vida eterna.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29714, 17, "Ao Rei eterno, ao Deus único, imortal e invisível, sejam honra e glória para todo o sempre. Amém.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29715, 18, "Timóteo, meu filho, dou-lhe esta instrução, segundo as profecias já proferidas a seu respeito, para que, seguindo-as, você combata o bom combate,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29716, 19, "mantendo a fé e a boa consciência que alguns rejeitaram e, por isso, naufragaram na fé.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29717, 20, "Entre eles estão Himeneu e Alexandre, os quais entreguei a Satanás, para que aprendam a não blasfemar.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29718, 1, "Antes de tudo, recomendo que se façam súplicas, orações, intercessões e ação de graças por todos os homens;", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29719, 2, "pelos reis e por todos os que exercem autoridade, para que tenhamos uma vida tranqüila e pacífica, com toda a piedade e dignidade.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29720, 3, "Isso é bom e agradável perante Deus, nosso Salvador,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29721, 4, "que deseja que todos os homens sejam salvos e cheguem ao conhecimento da verdade.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29722, 5, "Pois há um só Deus e um só mediador entre Deus e os homens: o homem Cristo Jesus,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29723, 6, "o qual se entregou a si mesmo como resgate por todos. Esse foi o testemunho dado em seu próprio tempo.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29724, 7, "Para isso fui designado pregador e apóstolo mestre da verdadeira fé aos gentios. Digo-lhes a verdade, não minto.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29725, 8, "Quero, pois, que os homens orem em todo lugar, levantando mãos santas, sem ira e sem discussões.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29726, 9, "Da mesma forma quero que as mulheres se vistam modestamente, com decência e discrição, não se adornando com tranças, nem ouro, nem pérolas, nem roupas caras,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29727, 10, "mas com boas obras, como convém a mulheres que professam adorar a Deus.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29728, 11, "A mulher deve aprender em silêncio, com toda a sujeição.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29729, 12, "Não permito que a mulher ensine, nem que tenha autoridade sobre o homem. Esteja, porém, em silêncio.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29730, 13, "Porque primeiro foi formado Adão, e depois Eva.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29731, 14, "E Adão não foi enganado, mas sim a mulher, que, tendo sido enganada, tornou-se transgressora.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29732, 15, "Entretanto, a mulher será salva dando à luz filhos — se elas permanecerem na fé, no amor e na santidade, com bom senso.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29733, 1, "Esta afirmação é digna de confiança: se alguém deseja ser bispo, deseja uma nobre função.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29734, 2, "É necessário, pois, que o bispo seja irrepreensível, marido de uma só mulher, sóbrio, prudente, respeitável, hospitaleiro e apto para ensinar;", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29735, 3, "não deve ser apegado ao vinho, nem violento, mas sim amável, pacífico e não apegado ao dinheiro.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29736, 4, "Ele deve governar bem sua própria família, tendo os filhos sujeitos a ele, com toda a dignidade.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29737, 5, "Pois, se alguém não sabe governar sua própria família, como poderá cuidar da igreja de Deus?", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29738, 6, "Não pode ser recém-convertido, para que não se ensoberbeça e caia na mesma condenação em que caiu o diabo.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29739, 7, "Também deve ter boa reputação perante os de fora, para que não caia em descrédito nem na cilada do diabo.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29740, 8, "Os diáconos igualmente devem ser dignos, homens de palavra, não amigos de muito vinho nem de lucros desonestos.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29741, 9, "Devem apegar-se ao mistério da fé com a consciência limpa.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29742, 10, "Devem ser primeiramente experimentados; depois, se não houver nada contra eles, que atuem como diáconos.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29743, 11, "As mulheres igualmente sejam dignas, não caluniadoras, mas sóbrias e confiáveis em tudo.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29744, 12, "O diácono deve ser marido de uma só mulher e governar bem seus filhos e sua própria casa.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29745, 13, "Os que servirem bem alcançarão uma excelente posição e grande determinação na fé em Cristo Jesus.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29746, 14, "Escrevo-lhe estas coisas embora espere ir vê-lo em breve;", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29747, 15, "mas, se eu demorar, saiba como as pessoas devem comportar-se na casa de Deus, que é a igreja do Deus vivo, coluna e fundamento da verdade.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29748, 16, "Não há dúvida de que é grande o mistério da piedade: Deus foi manifestado em corpo, justificado no Espírito, visto pelos anjos, pregado entre as nações, crido no mundo, recebido na glória.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29749, 1, "O Espírito diz claramente que nos últimos tempos alguns abandonarão a fé e seguirão espíritos enganadores e doutrinas de demônios.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29750, 2, "Tais ensinamentos vêm de homens hipócritas e mentirosos, que têm a consciência cauterizada", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29751, 3, "e proíbem o casamento e o consumo de alimentos que Deus criou para serem recebidos com ação de graças pelos que crêem e conhecem a verdade.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29752, 4, "Pois tudo o que Deus criou é bom, e nada deve ser rejeitado, se for recebido com ação de graças,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29753, 5, "pois é santificado pela palavra de Deus e pela oração.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29754, 6, "Se você transmitir essas instruções aos irmãos, será um bom ministro de Cristo Jesus, nutrido com as verdades da fé e da boa doutrina que tem seguido.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29755, 7, "Rejeite, porém, as fábulas profanas de velhas e exercite-se na piedade.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29756, 8, "O exercício físico é de pouco proveito; a piedade, porém, para tudo é proveitosa, porque tem promessa da vida presente e da futura.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29757, 9, "Esta é uma afirmação fiel e digna de plena aceitação.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29758, 10, "Se trabalhamos e lutamos é porque temos colocado a nossa esperança no Deus vivo, o Salvador de todos os homens, especialmente dos que crêem.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29759, 11, "Ordene e ensine estas coisas.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29760, 12, "Ninguém o despreze pelo fato de você ser jovem, mas seja um exemplo para os fiéis na palavra, no procedimento, no amor, na fé e na pureza.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29761, 13, "Até a minha chegada, dedique-se à leitura pública da Escritura, à exortação e ao ensino.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29762, 14, "Não negligencie o dom que lhe foi dado por mensagem profética com imposição de mãos dos presbíteros.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29763, 15, "Seja diligente nestas coisas; dedique-se inteiramente a elas, para que todos vejam o seu progresso.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29764, 16, "Atente bem para a sua própria vida e para a doutrina, perseverando nesses deveres, pois, fazendo isso, você salvará tanto a si mesmo quanto aos que o ouvem.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29765, 1, "Não repreenda asperamente ao homem idoso, mas exorte-o como se ele fosse seu pai; trate os jovens como a irmãos;", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29766, 2, "as mulheres idosas, como a mães; e as moças, como a irmãs, com toda a pureza.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29767, 3, "Trate adequadamente as viúvas que são realmente necessitadas.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29768, 4, "Mas se uma viúva tem filhos ou netos, que estes aprendam primeiramente a colocar a sua religião em prática, cuidando de sua própria família e retribuindo o bem recebido de seus pais e avós, pois isso agrada a Deus.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29769, 5, "A viúva realmente necessitada e desamparada põe sua esperança em Deus e persiste dia e noite em oração e em súplica.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29770, 6, "Mas a que vive para os prazeres, ainda que esteja viva, está morta.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29771, 7, "Ordene estas coisas para que sejam irrepreensíveis.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29772, 8, "Se alguém não cuida de seus parentes, e especialmente dos de sua própria família, negou a fé e é pior que um descrente.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29773, 9, "Nenhuma mulher deve ser inscrita na lista de viúvas, a não ser que tenha mais de sessenta anos de idade, tenha sido fiel a seu marido", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29774, 10, "e seja bem conhecida por suas boas obras, tais como criar filhos, ser hospitaleira, lavar os pés dos santos, socorrer os atribulados e dedicar-se a todo tipo de boa obra.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29775, 11, "Não inclua nessa lista as viúvas mais jovens, pois, quando os seus desejos sensuais superam a sua dedicação a Cristo, querem se casar.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29776, 12, "Assim, elas trazem condenação sobre si, por haverem rompido seu primeiro compromisso.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29777, 13, "Além disso, aprendem a ficar ociosas, andando de casa em casa; e não se tornam apenas ociosas, mas também fofoqueiras e indiscretas, falando coisas que não devem.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29778, 14, "Portanto, aconselho que as viúvas mais jovens se casem, tenham filhos, administrem suas casas e não dêem ao inimigo nenhum motivo para maledicência.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29779, 15, "Algumas, na verdade, já se desviaram, para seguir a Satanás.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29780, 16, "Se alguma mulher crente tem viúvas em sua família, deve ajudá-las. Não seja a igreja sobrecarregada com elas, a fim de que as viúvas realmente necessitadas sejam auxiliadas.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29781, 17, "Os presbíteros que lideram bem a igreja são dignos de dupla honra, especialmente aqueles cujo trabalho é a pregação e o ensino,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29782, 18, "pois a Escritura diz: ""Não amordace o boi enquanto está debulhando o cereal"", e ""o trabalhador merece o seu salário"".", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29783, 19, "Não aceite acusação contra um presbítero, se não for apoiada por duas ou três testemunhas.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29784, 20, "Os que pecarem deverão ser repreendidos em público, para que os demais também temam.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29785, 21, "Eu o exorto solenemente, diante de Deus, de Cristo Jesus e dos anjos eleitos, a que procure observar essas instruções sem parcialidade; e não faça nada por favoritismo.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29786, 22, "Não se precipite em impor as mãos sobre ninguém e não participe dos pecados dos outros. Conserve-se puro.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29787, 23, "Não continue a beber somente água; tome também um pouco de vinho, por causa do seu estômago e das suas freqüentes enfermidades.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29788, 24, "Os pecados de alguns são evidentes, mesmo antes de serem submetidos a julgamento; enquanto que os pecados de outros se manifestam posteriormente.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29789, 25, "Da mesma forma, as boas obras são evidentes, e as que não o são não podem permanecer ocultas.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29790, 1, "Todos os que estão sob o jugo da escravidão devem considerar seus senhores como dignos de todo o respeito, para que o nome de Deus e o nosso ensino não sejam blasfemados.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29791, 2, "Os que têm senhores crentes não devem ter por eles menos respeito, pelo fato de serem irmãos; pelo contrário, devem servi-los ainda melhor, porque os que se beneficiam do seu serviço são fiéis e amados. Ensine e recomende essas coisas.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29792, 3, "Se alguém ensina falsas doutrinas e não concorda com a sã doutrina de nosso Senhor Jesus Cristo e com o ensino que é segundo a piedade,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29793, 4, "é orgulhoso e nada entende. Esse tal mostra um interesse doentio por controvérsias e contendas acerca de palavras, que resultam em inveja, brigas, difamações, suspeitas malignas", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29794, 5, "e atritos constantes entre pessoas que têm a mente corrompida e que são privados da verdade, os quais pensam que a piedade é fonte de lucro.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29795, 6, "De fato, a piedade com contentamento é grande fonte de lucro,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29796, 7, "pois nada trouxemos para este mundo e dele nada podemos levar;", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29797, 8, "por isso, tendo o que comer e com que vestir-nos, estejamos com isso satisfeitos.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29798, 9, "Os que querem ficar ricos caem em tentação, em armadilhas e em muitos desejos descontrolados e nocivos, que levam os homens a mergulharem na ruína e na destruição,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29799, 10, "pois o amor ao dinheiro é raiz de todos os males. Algumas pessoas, por cobiçarem o dinheiro, desviaram-se da fé e se atormentaram a si mesmas com muitos sofrimentos.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29800, 11, "Você, porém, homem de Deus, fuja de tudo isso e busque a justiça, a piedade, a fé, o amor, a perseverança e a mansidão.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29801, 12, "Combata o bom combate da fé. Tome posse da vida eterna, para a qual você foi chamado e fez a boa confissão na presença de muitas testemunhas.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29802, 13, "Diante de Deus, que a tudo dá vida, e de Cristo Jesus, que diante de Pôncio Pilatos fez a boa confissão, eu lhe recomendo:", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29803, 14, "Guarde este mandamento imaculado, irrepreensível, até a manifestação de nosso Senhor Jesus Cristo,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29804, 15, "a qual Deus fará se cumprir no seu devido tempo. Ele é o bendito e único Soberano, o Rei dos reis e Senhor dos senhores,", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29805, 16, "o único que é imortal e habita em luz inacessível, a quem ninguém viu nem pode ver. A ele sejam honra e poder para sempre. Amém.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29806, 17, "Ordene aos que são ricos no presente mundo que não sejam arrogantes, nem ponham sua esperança na incerteza da riqueza, mas em Deus, que de tudo nos provê ricamente, para a nossa satisfação.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29807, 18, "Ordene-lhes que pratiquem o bem, sejam ricos em boas obras, generosos e prontos para repartir.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29808, 19, "Dessa forma, eles acumularão um tesouro para si mesmos, um firme fundamento para a era que há de vir, e assim alcançarão a verdadeira vida.", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29809, 20, "Timóteo, guarde o que lhe foi confiado. Evite as conversas inúteis e profanas e as idéias contraditórias do que é falsamente chamado conhecimento;", 53);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29810, 21, "professando-o, alguns desviaram-se da fé. A graça seja com vocês.", 53);