INSERT INTO verses (id, number, text, chapter_id) VALUES (29811, 1, "Paulo, apóstolo de Cristo Jesus pela vontade de Deus, segundo a promessa da vida que está em Cristo Jesus,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29812, 2, "a Timóteo, meu amado filho: Graça, misericórdia e paz da parte de Deus Pai e de Cristo Jesus, nosso Senhor.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29813, 3, "Dou graças a Deus, a quem sirvo com a consciência limpa, como o serviram os meus antepassados, ao lembrar-me constantemente de você noite e dia em minhas orações.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29814, 4, "Lembro-me das suas lágrimas e desejo muito vê-lo, para que a minha alegria seja completa.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29815, 5, "Recordo-me da sua fé não fingida, que primeiro habitou em sua avó Lóide e em sua mãe Eunice, e estou convencido de que também habita em você.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29816, 6, "Por essa razão, torno a lembrar-lhe que mantenha viva a chama do dom de Deus que está em você mediante a imposição das minhas mãos.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29817, 7, "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29818, 8, "Portanto, não se envergonhe de testemunhar do Senhor, nem de mim, que sou prisioneiro dele, mas suporte comigo os sofrimentos pelo evangelho, segundo o poder de Deus,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29819, 9, "que nos salvou e nos chamou com uma santa vocação, não em virtude das nossas obras, mas por causa da sua própria determinação e graça. Esta graça nos foi dada em Cristo Jesus desde os tempos eternos,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29820, 10, "sendo agora revelada pela manifestação de nosso Salvador, Cristo Jesus. Ele tornou inoperante a morte e trouxe à luz a vida e a imortalidade por meio do evangelho.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29821, 11, "Deste evangelho fui constituído pregador, apóstolo e mestre.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29822, 12, "Por essa causa também sofro, mas não me envergonho, porque sei em quem tenho crido e estou bem certo de que ele é poderoso para guardar o meu depósito até aquele dia.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29823, 13, "Retenha, com fé e amor em Cristo Jesus, o modelo da sã doutrina que você ouviu de mim.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29824, 14, "Quanto ao bom depósito, guarde-o por meio do Espírito Santo que habita em nós.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29825, 15, "Você sabe que todos os da província da Ásia me abandonaram, inclusive Fígelo e Hermógenes.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29826, 16, "O Senhor conceda misericórdia à casa de Onesíforo, porque muitas vezes ele me reanimou e não se envergonhou por eu estar preso;", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29827, 17, "pelo contrário, quando chegou a Roma procurou-me diligentemente até me encontrar.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29828, 18, "Conceda-lhe o Senhor que, naquele dia, encontre misericórdia da parte do Senhor! Você sabe muito bem quantos serviços ele me prestou em Éfeso.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29829, 1, "Portanto, você, meu filho, fortifique-se na graça que há em Cristo Jesus.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29830, 2, "E as coisas que me ouviu dizer na presença de muitas testemunhas, confie a homens fiéis que sejam também capazes de ensinar a outros.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29831, 3, "Suporte comigo os sofrimentos, como bom soldado de Cristo Jesus.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29832, 4, "Nenhum soldado se deixa envolver pelos negócios da vida civil, já que deseja agradar aquele que o alistou.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29833, 5, "Semelhantemente, nenhum atleta é coroado como vencedor, se não competir de acordo com as regras.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29834, 6, "O lavrador que trabalha arduamente deve ser o primeiro a participar dos frutos da colheita.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29835, 7, "Reflita no que estou dizendo, pois o Senhor lhe dará entendimento em tudo.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29836, 8, "Lembre-se de Jesus Cristo, ressuscitado dos mortos, descendente de Davi, conforme o meu evangelho,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29837, 9, "pelo qual sofro a ponto de estar preso como criminoso; contudo a palavra de Deus não está presa.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29838, 10, "Por isso, tudo suporto por causa dos eleitos, para que também eles alcancem a salvação que está em Cristo Jesus, com glória eterna.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29839, 11, "Esta palavra é digna de confiança: Se morremos com ele, com ele também viveremos;", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29840, 12, "se perseveramos, com ele também reinaremos. Se o negamos, ele também nos negará;", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29841, 13, "se somos infiéis, ele permanece fiel, pois não pode negar-se a si mesmo.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29842, 14, "Continue a lembrar essas coisas a todos, advertindo-os solenemente diante de Deus, para que não se envolvam em discussões acerca de palavras; isso não tem proveito, e serve apenas para perverter os ouvintes.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29843, 15, "Procure apresentar-se a Deus aprovado, como obreiro que não tem do que se envergonhar, que maneja corretamente a palavra da verdade.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29844, 16, "Evite as conversas inúteis e profanas, pois os que se dão a isso prosseguem cada vez mais para a impiedade.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29845, 17, "O ensino deles alastra como câncer; entre eles estão Himeneu e Fileto.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29846, 18, "Estes se desviaram da verdade, dizendo que a ressurreição já aconteceu, e assim a alguns pervertem a fé.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29847, 19, "Entretanto, o firme fundamento de Deus permanece inabalável e selado com esta inscrição: ""O Senhor conhece quem lhe pertence"" e ""afaste-se da iniqüidade todo aquele que confessa o nome do Senhor"".", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29848, 20, "Numa grande casa há vasos não apenas de ouro e prata, mas também de madeira e barro; alguns para fins honrosos, outros para fins desonrosos.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29849, 21, "Se alguém se purificar dessas coisas, será vaso para honra, santificado, útil para o Senhor e preparado para toda boa obra.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29850, 22, "Fuja dos desejos malignos da juventude e siga a justiça, a fé, o amor e a paz, juntamente com os que, de coração puro, invocam o Senhor.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29851, 23, "Evite as controvérsias tolas e fúteis, pois você sabe que acabam em brigas.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29852, 24, "Ao servo do Senhor não convém brigar mas, sim, ser amável para com todos, apto para ensinar, paciente.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29853, 25, "Deve corrigir com mansidão os que se lhe opõem, na esperança de que Deus lhes conceda o arrependimento, levando-os ao conhecimento da verdade,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29854, 26, "para que assim voltem à sobriedade e escapem da armadilha do diabo, que os aprisionou para fazerem a sua vontade.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29855, 1, "Saiba disto: nos últimos dias sobrevirão tempos terríveis.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29856, 2, "Os homens serão egoístas, avarentos, presunçosos, arrogantes, blasfemos, desobedientes aos pais, ingratos, ímpios,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29857, 3, "sem amor pela família, irreconciliáveis, caluniadores, sem domínio próprio, cruéis, inimigos do bem,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29858, 4, "traidores, precipitados, soberbos, mais amantes dos prazeres do que amigos de Deus,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29859, 5, "tendo aparência de piedade, mas negando o seu poder. Afaste-se também destes.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29860, 6, "São estes os que se introduzem pelas casas e conquistam mulherzinhas sobrecarregadas de pecados, as quais se deixam levar por toda espécie de desejos.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29861, 7, "Elas estão sempre aprendendo, mas não conseguem nunca de chegar ao conhecimento da verdade.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29862, 8, "Como Janes e Jambres se opuseram a Moisés, esses também resistem à verdade. A mente deles é depravada; são reprovados na fé.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29863, 9, "Não irão longe, porém; como no caso daqueles, a sua insensatez se tornará evidente a todos.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29864, 10, "Mas você tem seguido de perto o meu ensino, a minha conduta, o meu propósito, a minha fé, a minha paciência, o meu amor, a minha perseverança,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29865, 11, "as perseguições e os sofrimentos que enfrentei, coisas que me aconteceram em Antioquia, Icônio e Listra. Quanta perseguição suportei! Mas, de todas essas coisas o Senhor me livrou!", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29866, 12, "De fato, todos os que desejam viver piedosamente em Cristo Jesus serão perseguidos.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29867, 13, "Contudo, os perversos e impostores irão de mal a pior, enganando e sendo enganados.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29868, 14, "Quanto a você, porém, permaneça nas coisas que aprendeu e das quais tem convicção, pois você sabe de quem o aprendeu.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29869, 15, "Porque desde criança você conhece as sagradas letras, que são capazes de torná-lo sábio para a salvação mediante a fé em Cristo Jesus.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29870, 16, "Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29871, 17, "para que o homem de Deus seja apto e plenamente preparado para toda boa obra.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29872, 1, "Na presença de Deus e de Cristo Jesus, que há de julgar os vivos e os mortos por sua manifestação e por seu Reino, eu o exorto solenemente:", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29873, 2, "Pregue a palavra, esteja preparado a tempo e fora de tempo, repreenda, corrija, exorte com toda a paciência e doutrina.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29874, 3, "Pois virá o tempo em que não suportarão a sã doutrina; pelo contrário, sentindo coceira nos ouvidos, segundo os seus próprios desejos juntarão mestres para si mesmos.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29875, 4, "Eles se recusarão a dar ouvidos à verdade, voltando-se para os mitos.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29876, 5, "Você, porém, seja sóbrio em tudo, suporte os sofrimentos, faça a obra de um evangelista, cumpra plenamente o seu ministério.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29877, 6, "Eu já estou sendo derramado como uma oferta de bebida. Está próximo o tempo da minha partida.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29878, 7, "Combati o bom combate, terminei a corrida, guardei a fé.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29879, 8, "Agora me está reservada a coroa da justiça, que o Senhor, justo Juiz, me dará naquele dia; e não somente a mim, mas também a todos os que amam a sua vinda.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29880, 9, "Procure vir logo ao meu encontro,", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29881, 10, "pois Demas, amando este mundo, abandonou-me e foi para Tessalônica. Crescente foi para a Galácia, e Tito, para a Dalmácia.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29882, 11, "Só Lucas está comigo. Traga Marcos com você, porque ele me é útil para o ministério.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29883, 12, "Enviei Tíquico a Éfeso.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29884, 13, "Quando você vier, traga a capa que deixei na casa de Carpo, em Trôade, e os meus livros, especialmente os pergaminhos.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29885, 14, "Alexandre, o ferreiro, causou-me muitos males. O Senhor lhe dará a retribuição pelo que fez.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29886, 15, "Previna-se contra ele, porque se opôs fortemente às nossas palavras.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29887, 16, "Na minha primeira defesa, ninguém apareceu para me apoiar; todos me abandonaram. Que isso não lhes cobrado.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29888, 17, "Mas o Senhor permaneceu ao meu lado e me deu forças, para que por mim a mensagem fosse plenamente proclamada, e todos os gentios a ouvissem. E eu fui libertado da boca do leão.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29889, 18, "O Senhor me livrará de toda obra maligna e me levará a salvo para o seu Reino celestial. A ele seja a glória para todo o sempre. Amém.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29890, 19, "Saudações a Priscila e Áqüila, e à casa de Onesíforo.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29891, 20, "Erasto permaneceu em Corinto, mas deixei Trófimo doente em Mileto.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29892, 21, "Procure vir antes do inverno. Êubulo, Prudente, Lino, Cláudia e todos os irmãos enviam-lhe saudações.", 54);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29893, 22, "O Senhor seja com o seu espírito. A graça seja com vocês.", 54);