INSERT INTO verses (id, number, text, chapter_id) VALUES (29467, 1, "Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Timóteo,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29468, 2, "aos santos e fiéis irmãos em Cristo que estão em Colossos: A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29469, 3, "Sempre agradecemos a Deus, o Pai de nosso Senhor Jesus Cristo, quando oramos por vocês,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29470, 4, "pois temos ouvido falar da fé que vocês têm em Cristo Jesus e do amor por todos os santos,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29471, 5, "por causa da esperança que lhes está reservada nos céus, a respeito da qual vocês ouviram por meio da palavra da verdade, o evangelho", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29472, 6, "que chegou até vocês. Por todo o mundo este evangelho vai frutificando e crescendo, como também ocorre entre vocês, desde o dia em que o ouviram e entenderam a graça de Deus em toda a sua verdade.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29473, 7, "Vocês o aprenderam de Epafras, nosso amado cooperador, fiel ministro de Cristo para conosco,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29474, 8, "que também nos falou do amor que vocês têm no Espírito.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29475, 9, "Por essa razão, desde o dia em que o ouvimos, não deixamos de orar por vocês e de pedir que sejam cheios do pleno conhecimento da vontade de Deus, com toda a sabedoria e entendimento espiritual.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29476, 10, "E isso para que vocês vivam de maneira digna do Senhor e em tudo possam agradá-lo, frutificando em toda boa obra, crescendo no conhecimento de Deus e", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29477, 11, "sendo fortalecidos com todo o poder, de acordo com a força da sua glória, para que tenham toda a perseverança e paciência com alegria,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29478, 12, "dando graças ao Pai, que nos tornou dignos de participar da herança dos santos no reino da luz.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29479, 13, "Pois ele nos resgatou do domínio das trevas e nos transportou para o Reino do seu Filho amado,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29480, 14, "em quem temos a redenção, a saber, o perdão dos pecados.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29481, 15, "Ele é a imagem do Deus invisível, o primogênito de toda a criação,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29482, 16, "pois nele foram criadas todas as coisas nos céus e na terra, as visíveis e as invisíveis, sejam tronos ou soberanias, poderes ou autoridades; todas as coisas foram criadas por ele e para ele.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29483, 17, "Ele é antes de todas as coisas, e nele tudo subsiste.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29484, 18, "Ele é a cabeça do corpo, que é a igreja; é o princípio e o primogênito dentre os mortos, para que em tudo tenha a supremacia.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29485, 19, "Pois foi do agrado de Deus que nele habitasse toda a plenitude,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29486, 20, "e por meio dele reconciliasse consigo todas as coisas, tanto as que estão na terra quanto as que estão no céu, estabelecendo a paz pelo seu sangue derramado na cruz.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29487, 21, "Antes vocês estavam separados de Deus e, em suas mentes, eram inimigos por causa do mau procedimento de vocês.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29488, 22, "Mas agora ele os reconciliou pelo corpo físico de Cristo, mediante a morte, para apresentá-los diante dele santos, inculpáveis e livres de qualquer acusação,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29489, 23, "desde que continuem alicerçados e firmes na fé, sem se afastarem da esperança do evangelho, que vocês ouviram e que tem sido proclamado a todos os que estão debaixo do céu. Esse é o evangelho do qual eu, Paulo, me tornei ministro.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29490, 24, "Agora me alegro em meus sofrimentos por vocês, e completo no meu corpo o que resta das aflições de Cristo, em favor do seu corpo, que é a igreja.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29491, 25, "Dela me tornei ministro de acordo com a responsabilidade por Deus a mim atribuída de apresentar-lhes plenamente a palavra de Deus,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29492, 26, "o mistério que esteve oculto durante épocas e gerações, mas que agora foi manifestado a seus santos.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29493, 27, "A eles quis Deus dar a conhecer entre os gentios a gloriosa riqueza deste mistério, que é Cristo em vocês, a esperança da glória.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29494, 28, "Nós o proclamamos, advertindo e ensinando a cada um com toda a sabedoria, a fim de que apresentemos todo homem perfeito em Cristo.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29495, 29, "Para isso eu me esforço, lutando conforme a sua força, que atua poderosamente em mim.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29496, 1, "Quero que vocês saibam quanto estou lutando por vocês, pelos que estão em Laodicéia e por todos os que ainda não me conhecem pessoalmente.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29497, 2, "Esforço-me para que eles sejam fortalecidos em seus corações, estejam unidos em amor e alcancem toda a riqueza do pleno entendimento, a fim de conhecerem plenamente o mistério de Deus, a saber, Cristo.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29498, 3, "Nele estão escondidos todos os tesouros da sabedoria e do conhecimento.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29499, 4, "Eu lhes digo isso para que ninguém os engane com argumentos aparentemente convincentes.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29500, 5, "Porque, embora esteja fisicamente ausente, estou presente com vocês em espírito, e alegro-me em ver como estão vivendo em ordem e como está firme a fé que vocês têm em Cristo.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29501, 6, "Portanto, assim como vocês receberam a Cristo Jesus, o Senhor, continuem a viver nele,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29502, 7, "enraizados e edificados nele, firmados na fé, como foram ensinados, transbordando de gratidão.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29503, 8, "Tenham cuidado para que ninguém os escravize a filosofias vãs e enganosas, que se fundamentam nas tradições humanas e nos princípios elementares deste mundo, e não em Cristo.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29504, 9, "Pois em Cristo habita corporalmente toda a plenitude da divindade,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29505, 10, "e, por estarem nele, que é o Cabeça de todo poder e autoridade, vocês receberam a plenitude.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29506, 11, "Nele também vocês foram circuncidados, não com uma circuncisão feita por mãos humanas, mas com a circuncisão feita por Cristo, que é o despojar do corpo da carne.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29507, 12, "Isso aconteceu quando vocês foram sepultados com ele no batismo, e com ele foram ressuscitados mediante a fé no poder de Deus que o ressuscitou dentre os mortos.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29508, 13, "Quando vocês estavam mortos em pecados e na incircuncisão da sua carne, Deus os vivificou juntamente com Cristo. Ele nos perdoou todas as transgressões,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29509, 14, "e cancelou a escrita de dívida, que consistia em ordenanças, e que nos era contrária. Ele a removeu, pregando-a na cruz,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29510, 15, "e, tendo despojado os poderes e as autoridades, fez deles um espetáculo público, triunfando sobre eles na cruz.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29511, 16, "Portanto, não permitam que ninguém os julgue pelo que vocês comem ou bebem, ou com relação a alguma festividade religiosa ou à celebração das luas novas ou dos dias de sábado.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29512, 17, "Estas coisas são sombras do que haveria de vir; a realidade, porém, encontra-se em Cristo.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29513, 18, "Não permitam que ninguém que tenha prazer numa falsa humildade e na adoração de anjos os impeça de alcançar o prêmio. Tal pessoa conta detalhadamente suas visões, e sua mente carnal a torna orgulhosa.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29514, 19, "Trata-se de alguém que não está unido à Cabeça, a partir da qual todo o corpo, sustentado e unido por seus ligamentos e juntas, efetua o crescimento dado por Deus.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29515, 20, "Já que vocês morreram com Cristo para os princípios elementares deste mundo, por que é que vocês, então, como se ainda pertencessem a ele, se submetem a regras:", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29516, 21, """Não manuseie! "" ""Não prove! "" ""Não toque! ""?", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29517, 22, "Todas essas coisas estão destinadas a perecer pelo uso, pois se baseiam em mandamentos e ensinos humanos.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29518, 23, "Essas regras têm, de fato, aparência de sabedoria, com sua pretensa religiosidade, falsa humildade e severidade com o corpo, mas não têm valor algum para refrear os impulsos da carne.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29519, 1, "Portanto, já que vocês ressuscitaram com Cristo, procurem as coisas que são do alto, onde Cristo está assentado à direita de Deus.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29520, 2, "Mantenham o pensamento nas coisas do alto, e não nas coisas terrenas.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29521, 3, "Pois vocês morreram, e agora a sua vida está escondida com Cristo em Deus.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29522, 4, "Quando Cristo, que é a sua vida, for manifestado, então vocês também serão manifestados com ele em glória.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29523, 5, "Assim, façam morrer tudo o que pertence à natureza terrena de vocês: imoralidade sexual, impureza, paixão, desejos maus e a ganância, que é idolatria.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29524, 6, "É por causa dessas coisas que vem a ira de Deus sobre os que vivem na desobediência,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29525, 7, "as quais vocês praticaram no passado, quando costumavam viver nelas.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29526, 8, "Mas agora, abandonem todas estas coisas: ira, indignação, maldade, maledicência e linguagem indecente no falar.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29527, 9, "Não mintam uns aos outros, visto que vocês já se despiram do velho homem com suas práticas", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29528, 10, "e se revestiram do novo, o qual está sendo renovado em conhecimento, à imagem do seu Criador.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29529, 11, "Nessa nova vida já não há diferença entre grego e judeu, circunciso e incircunciso, bárbaro e cita, escravo e livre, mas Cristo é tudo e está em todos.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29530, 12, "Portanto, como povo escolhido de Deus, santo e amado, revistam-se de profunda compaixão, bondade, humildade, mansidão e paciência.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29531, 13, "Suportem-se uns aos outros e perdoem as queixas que tiverem uns contra os outros. Perdoem como o Senhor lhes perdoou.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29532, 14, "Acima de tudo, porém, revistam-se do amor, que é o elo perfeito.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29533, 15, "Que a paz de Cristo seja o juiz em seus corações, visto que vocês foram chamados a viver em paz, como membros de um só corpo. E sejam agradecidos.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29534, 16, "Habite ricamente em vocês a palavra de Cristo; ensinem e aconselhem-se uns aos outros com toda a sabedoria, e cantem salmos, hinos e cânticos espirituais com gratidão a Deus em seus corações.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29535, 17, "Tudo o que fizerem, seja em palavra ou em ação, façam-no em nome do Senhor Jesus, dando por meio dele graças a Deus Pai.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29536, 18, "Mulheres, sujeitem-se a seus maridos, como convém a quem está no Senhor.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29537, 19, "Maridos, amem suas mulheres e não as tratem com amargura.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29538, 20, "Filhos, obedeçam a seus pais em tudo, pois isso agrada ao Senhor.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29539, 21, "Pais, não irritem seus filhos, para que eles não se desanimem.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29540, 22, "Escravos, obedeçam em tudo a seus senhores terrenos, não somente para agradar os homens quando eles estão observando, mas com sinceridade de coração, pelo fato de vocês temerem ao Senhor.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29541, 23, "Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens,", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29542, 24, "sabendo que receberão do Senhor a recompensa da herança. É a Cristo, o Senhor, que vocês estão servindo.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29543, 25, "Quem cometer injustiça receberá de volta injustiça, e não haverá exceção para ninguém.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29544, 1, "Senhores, dêem aos seus escravos o que é justo e direito, sabendo que vocês também têm um Senhor no céu.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29545, 2, "Dediquem-se à oração, estejam alertas e sejam agradecidos.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29546, 3, "Ao mesmo tempo, orem também por nós, para que Deus abra uma porta para a nossa mensagem, a fim de que possamos proclamar o mistério de Cristo, pelo qual estou preso.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29547, 4, "Orem para que eu possa manifestá-lo abertamente, como me cumpre fazê-lo.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29548, 5, "Sejam sábios no procedimento para com os de fora; aproveitem ao máximo todas as oportunidades.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29549, 6, "O seu falar seja sempre agradável e temperado com sal, para que saibam como responder a cada um.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29550, 7, "Tíquico lhes informará todas as coisas a meu respeito. Ele é um irmão amado, ministro fiel e cooperador no serviço do Senhor.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29551, 8, "Eu o envio a vocês precisamente com o propósito de que saibam de tudo o que se passa conosco, e para que ele fortaleça os seus corações.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29552, 9, "Ele irá com Onésimo, fiel e amado irmão, que é um de vocês. Eles irão contar-lhes tudo o que está acontecendo aqui.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29553, 10, "Aristarco, meu companheiro de prisão, envia-lhes saudações, bem como Marcos, primo de Barnabé. Vocês receberam instruções a respeito de Marcos, e se ele for visitá-los, recebam-no.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29554, 11, "Jesus, chamado Justo, também envia saudações. Estes são os únicos da circuncisão que são meus cooperadores em favor do Reino de Deus. Eles têm sido uma fonte de ânimo para mim.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29555, 12, "Epafras, que é um de vocês e servo de Cristo Jesus, envia saudações. Ele está sempre batalhando por vocês em oração, para que, como pessoas maduras e plenamente convictas, continuem firmes em toda a vontade de Deus.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29556, 13, "Dele dou testemunho de que se esforça muito por vocês e pelos que estão em Laodicéia e em Hierápolis.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29557, 14, "Lucas, o médico amado, e Demas, enviam saudações.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29558, 15, "Saúdem os irmãos de Laodicéia, bem como Ninfa e a igreja que se reúne em sua casa.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29559, 16, "Depois que esta carta for lida entre vocês, façam que também seja lida na igreja dos laodicenses, e que vocês igualmente leiam a carta de Laodicéia.", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29560, 17, "Digam a Arquipo: ""Cuide em cumprir o ministério que você recebeu no Senhor"".", 50);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29561, 18, "Eu, Paulo, escrevo esta saudação de próprio punho. Lembrem-se das minhas algemas. A graça seja com vocês.", 50);