INSERT INTO verses (id, number, text, chapter_id) VALUES (29940, 1, "Paulo, prisioneiro de Cristo Jesus, e o irmão Timóteo, a você, Filemom, nosso amado cooperador,", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29941, 2, "à irmã Áfia, a Arquipo, nosso companheiro de lutas, e à igreja que se reúne com você em sua casa.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29942, 3, "A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29943, 4, "Sempre dou graças a meu Deus, lembrando-me de você nas minhas orações,", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29944, 5, "porque ouço falar da sua fé no Senhor Jesus e do seu amor por todos os santos.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29945, 6, "Oro para que a comunhão que procede da sua fé seja eficaz no pleno conhecimento de todo o bem que temos em Cristo.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29946, 7, "Seu amor me tem dado grande alegria e consolação, porque você, irmão, tem reanimado o coração dos santos.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29947, 8, "Por isso, mesmo tendo em Cristo plena liberdade para mandar que você cumpra o seu dever,", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29948, 9, "prefiro fazer um apelo com base no amor. Eu, Paulo, já velho, e agora também prisioneiro de Cristo Jesus,", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29949, 10, "apelo em favor de meu filho Onésimo, que gerei enquanto estava preso.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29950, 11, "Ele antes lhe era inútil, mas agora é útil, tanto para você quanto para mim.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29951, 12, "Mando-o de volta a você, como se fosse o meu próprio coração.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29952, 13, "Gostaria de mantê-lo comigo para que me ajudasse em seu lugar enquanto estou preso por causa do evangelho.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29953, 14, "Mas não quis fazer nada sem a sua permissão, para que qualquer favor que você fizer seja espontâneo, e não forçado.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29954, 15, "Talvez ele tenha sido separado de você por algum tempo, para que você o tivesse de volta para sempre,", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29955, 16, "não mais como escravo, mas, acima de escravo, como irmão amado. Para mim ele é um irmão muito amado, e ainda mais para você, tanto como pessoa quanto como cristão.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29956, 17, "Assim, se você me considera companheiro na fé, receba-o como se estivesse recebendo a mim.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29957, 18, "Se ele o prejudicou em algo ou lhe deve alguma coisa, ponha na minha conta.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29958, 19, "Eu, Paulo, escrevo de próprio punho: Eu pagarei — para não dizer que você me deve a sua própria pessoa.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29959, 20, "Sim, irmão, eu gostaria de receber de você algum benefício por estarmos no Senhor. Reanime o meu coração em Cristo!", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29960, 21, "Escrevo-lhe certo de que você me obedecerá, sabendo que fará ainda mais do lhe que peço.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29961, 22, "Além disso, prepare-me um aposento, porque, graças às suas orações, espero poder ser restituído a vocês.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29962, 23, "Epafras, meu companheiro de prisão por causa de Cristo Jesus, envia-lhe saudações,", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29963, 24, "assim como também Marcos, Aristarco, Demas e Lucas, meus cooperadores.", 56);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29964, 25, "A graça do Senhor Jesus Cristo seja com o espírito de todos vocês.", 56);