INSERT INTO verses (id, number, text, chapter_id) VALUES (29363, 1, "Paulo e Timóteo, servos de Cristo Jesus, a todos os santos em Cristo Jesus que estão em Filipos, juntamente com os bispos e diáconos:", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29364, 2, "A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29365, 3, "Agradeço a meu Deus toda vez que me lembro de vocês.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29366, 4, "Em todas as minhas orações em favor de vocês, sempre oro com alegria", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29367, 5, "por causa da cooperação que vocês têm dado ao evangelho, desde o primeiro dia até agora.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29368, 6, "Estou convencido de que aquele que começou boa obra em vocês, vai completá-la até o dia de Cristo Jesus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29369, 7, "É justo que eu assim me sinta a respeito de todos vocês, uma vez que os tenho em meu coração, pois, quer nas correntes que me prendem quer defendendo e confirmando o evangelho, todos vocês participam comigo da graça de Deus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29370, 8, "Deus é minha testemunha de como tenho saudade de todos vocês, com a profunda afeição de Cristo Jesus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29371, 9, "Esta é a minha oração: que o amor de vocês aumente cada vez mais em conhecimento e em toda a percepção,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29372, 10, "para discernirem o que é melhor, a fim de serem puros e irrepreensíveis até o dia de Cristo,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29373, 11, "cheios do fruto da justiça, fruto que vem por meio de Jesus Cristo, para glória e louvor de Deus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29374, 12, "Quero que saibam, irmãos, que aquilo que me aconteceu tem antes servido para o progresso do evangelho.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29375, 13, "Como resultado, tornou-se evidente a toda a guarda do palácio e a todos os demais que estou na prisão por causa de Cristo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29376, 14, "E a maioria dos irmãos, motivados no Senhor pela minha prisão, estão anunciando a palavra com maior determinação e destemor.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29377, 15, "É verdade que alguns pregam a Cristo por inveja e rivalidade, mas outros o fazem de boa vontade.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29378, 16, "Estes o fazem por amor, sabendo que aqui me encontro para a defesa do evangelho.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29379, 17, "Aqueles pregam a Cristo por ambição egoísta, sem sinceridade, pensando que me podem causar sofrimento enquanto estou preso.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29380, 18, "Mas, que importa? O importante é que de qualquer forma, seja por motivos falsos ou verdadeiros, Cristo está sendo pregado, e por isso me alegro. De fato, continuarei a alegrar-me,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29381, 19, "pois sei que o que me aconteceu resultará em minha libertação, graças às orações de vocês e ao auxílio do Espírito de Jesus Cristo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29382, 20, "Aguardo ansiosamente e espero que em nada serei envergonhado. Pelo contrário, com toda a determinação de sempre, também agora Cristo será engrandecido em meu corpo, quer pela vida quer pela morte;", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29383, 21, "porque para mim o viver é Cristo e o morrer é lucro.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29384, 22, "Caso continue vivendo no corpo, terei fruto do meu trabalho. E já não sei o que escolher!", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29385, 23, "Estou pressionado dos dois lados: desejo partir e estar com Cristo, o que é muito melhor;", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29386, 24, "contudo, é mais necessário, por causa de vocês, que eu permaneça no corpo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29387, 25, "Convencido disso, sei que vou permanecer e continuar com todos vocês, para o seu progresso e alegria na fé,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29388, 26, "a fim de que, pela minha presença, outra vez a exultação de vocês em Cristo Jesus transborde por minha causa.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29389, 27, "Não importa o que aconteça, exerçam a sua cidadania de maneira digna do evangelho de Cristo, para que assim, quer eu vá e os veja, quer apenas ouça a seu respeito em minha ausência, fique eu sabendo que vocês permanecem firmes num só espírito, lutando unânimes pela fé evangélica,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29390, 28, "sem de forma alguma deixar-se intimidar por aqueles que se opõem a vocês. Para eles isso é sinal de destruição, mas para vocês de salvação, e isso da parte de Deus;", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29391, 29, "pois a vocês foi dado o privilégio de, não apenas crer em Cristo, mas também de sofrer por ele,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29392, 30, "já que estão passando pelo mesmo combate que me viram enfrentar e agora ouvem que ainda enfrento.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29393, 1, "Se por estarmos em Cristo, nós temos alguma motivação, alguma exortação de amor, alguma comunhão no Espírito, alguma profunda afeição e compaixão,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29394, 2, "completem a minha alegria, tendo o mesmo modo de pensar, o mesmo amor, um só espírito e uma só atitude.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29395, 3, "Nada façam por ambição egoísta ou por vaidade, mas humildemente considerem os outros superiores a si mesmos.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29396, 4, "Cada um cuide, não somente dos seus interesses, mas também dos interesses dos outros.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29397, 5, "Seja a atitude de vocês a mesma de Cristo Jesus,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29398, 6, "que, embora sendo Deus, não considerou que o ser igual a Deus era algo a que devia apegar-se;", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29399, 7, "mas esvaziou-se a si mesmo, vindo a ser servo, tornando-se semelhante aos homens.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29400, 8, "E, sendo encontrado em forma humana, humilhou-se a si mesmo e foi obediente até à morte, e morte de cruz!", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29401, 9, "Por isso Deus o exaltou à mais alta posição e lhe deu o nome que está acima de todo nome,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29402, 10, "para que ao nome de Jesus se dobre todo joelho, no céu, na terra e debaixo da terra,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29403, 11, "e toda língua confesse que Jesus Cristo é o Senhor, para a glória de Deus Pai.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29404, 12, "Assim, meus amados, como sempre vocês obedeceram, não apenas em minha presença, porém muito mais agora na minha ausência, ponham em ação a salvação de vocês com temor e tremor,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29405, 13, "pois é Deus quem efetua em vocês tanto o querer quanto o realizar, de acordo com a boa vontade dele.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29406, 14, "Façam tudo sem queixas nem discussões,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29407, 15, "para que venham a tornar-se puros e irrepreensíveis, filhos de Deus inculpáveis no meio de uma geração corrompida e depravada, na qual vocês brilham como estrelas no universo,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29408, 16, "retendo firmemente a palavra da vida. Assim, no dia de Cristo eu me orgulharei de não ter corrido nem me esforçado inutilmente.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29409, 17, "Contudo, mesmo que eu esteja sendo derramado como oferta de bebida sobre o serviço que provém da fé que vocês têm, o sacrifício que oferecem a Deus, estou alegre e me regozijo com todos vocês.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29410, 18, "Estejam vocês também alegres, e regozijem-se comigo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29411, 19, "Espero no Senhor Jesus enviar-lhes Timóteo brevemente, para que eu também me sinta animado quando receber notícias de vocês.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29412, 20, "Não tenho ninguém como ele, que tenha interesse sincero pelo bem-estar de vocês,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29413, 21, "pois todos buscam os seus próprios interesses e não os de Jesus Cristo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29414, 22, "Mas vocês sabem que Timóteo foi aprovado, porque serviu comigo no trabalho do evangelho como um filho ao lado de seu pai.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29415, 23, "Portanto, é ele quem espero enviar, tão logo me certifique da minha situação,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29416, 24, "confiando no Senhor que em breve também poderei ir.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29417, 25, "Contudo, penso que será necessário enviar-lhes de volta Epafrodito, meu irmão, cooperador e companheiro de lutas, mensageiro que vocês enviaram para atender às minhas necessidades.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29418, 26, "Pois ele tem saudade de todos vocês e está angustiado porque ficaram sabendo que ele esteve doente.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29419, 27, "De fato, ficou doente e quase morreu. Mas Deus teve misericórdia dele, e não somente dele, mas também de mim, para que eu não tivesse tristeza sobre tristeza.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29420, 28, "Por isso, logo o enviarei, para que, quando o virem novamente, fiquem alegres e eu tenha menos tristeza.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29421, 29, "E peço que vocês o recebam no Senhor com grande alegria e honrem a homens como este,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29422, 30, "porque ele quase morreu por amor à causa de Cristo, arriscando a vida para suprir a ajuda que vocês não me podiam dar.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29423, 1, "Finalmente, meus irmãos, alegrem-se no Senhor! Escrever-lhes de novo as mesmas coisas não é cansativo para mim e é uma segurança para vocês.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29424, 2, "Cuidado com os cães, cuidado com esses que praticam o mal, cuidado com a falsa circuncisão!", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29425, 3, "Pois nós é que somos a circuncisão, nós que adoramos pelo Espírito de Deus, que nos gloriamos em Cristo Jesus e não temos confiança alguma na carne,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29426, 4, "embora eu mesmo tivesse razões para ter tal confiança. Se alguém pensa que tem razões para confiar na carne, eu ainda mais:", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29427, 5, "circuncidado no oitavo dia de vida, pertencente ao povo de Israel, à tribo de Benjamim, verdadeiro hebreu; quanto à lei, fariseu;", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29428, 6, "quanto ao zelo, perseguidor da igreja; quanto à justiça que há na lei, irrepreensível.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29429, 7, "Mas o que para mim era lucro, passei a considerar perda, por causa de Cristo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29430, 8, "Mais do que isso, considero tudo como perda, comparado com a suprema grandeza do conhecimento de Cristo Jesus, meu Senhor, por cuja causa perdi todas as coisas. Eu as considero como esterco para poder ganhar a Cristo", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29431, 9, "e ser encontrado nele, não tendo a minha própria justiça que procede da lei, mas a que vem mediante a fé em Cristo, a justiça que procede de Deus e se baseia na fé.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29432, 10, "Quero conhecer a Cristo, ao poder da sua ressurreição e à participação em seus sofrimentos, tornando-me como ele em sua morte", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29433, 11, "para, de alguma forma, alcançar a ressurreição dentre os mortos.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29434, 12, "Não que eu já tenha obtido tudo isso ou tenha sido aperfeiçoado, mas prossigo para alcançá-lo, pois para isso também fui alcançado por Cristo Jesus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29435, 13, "Irmãos, não penso que eu mesmo já o tenha alcançado, mas uma coisa faço: esquecendo-me das coisas que ficaram para trás e avançando para as que estão adiante,", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29436, 14, "prossigo para o alvo, a fim de ganhar o prêmio do chamado celestial de Deus em Cristo Jesus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29437, 15, "Todos nós que alcançamos a maturidade devemos ver as coisas dessa forma, e se em algum aspecto vocês pensam de modo diferente, isso também Deus lhes esclarecerá.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29438, 16, "Tão-somente vivamos de acordo com o que já alcançamos.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29439, 17, "Irmãos, sigam unidos o meu exemplo e observem os que vivem de acordo com o padrão que lhes apresentamos.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29440, 18, "Pois, como já lhes disse repetidas vezes, e agora repito com lágrimas, há muitos que vivem como inimigos da cruz de Cristo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29441, 19, "Quanto a estes, o seu destino é a perdição, o seu deus é o estômago e têm orgulho do que é vergonhoso; eles só pensam nas coisas terrenas.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29442, 20, "A nossa cidadania, porém, está nos céus, de onde esperamos ansiosamente um Salvador, o Senhor Jesus Cristo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29443, 21, "Pelo poder que o capacita a colocar todas as coisas debaixo do seu domínio, ele transformará os nossos corpos humilhados, para serem semelhantes ao seu corpo glorioso.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29444, 1, "Portanto, meus irmãos, a quem amo e de quem tenho saudade, vocês que são a minha alegria e a minha coroa, permaneçam assim firmes no Senhor, ó amados!", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29445, 2, "O que eu rogo a Evódia e também a Síntique é que vivam em harmonia no Senhor.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29446, 3, "Sim, e peço a você, leal companheiro de jugo, que as ajude; pois lutaram ao meu lado na causa do evangelho, com Clemente e meus demais cooperadores. Os seus nomes estão no livro da vida.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29447, 4, "Alegrem-se sempre no Senhor. Novamente direi: alegrem-se!", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29448, 5, "Seja a amabilidade de vocês conhecida por todos. Perto está o Senhor.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29449, 6, "Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29450, 7, "E a paz de Deus, que excede todo o entendimento, guardará os seus corações e as suas mentes em Cristo Jesus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29451, 8, "Finalmente, irmãos, tudo o que for verdadeiro, tudo o que for nobre, tudo o que for correto, tudo o que for puro, tudo o que for amável, tudo o que for de boa fama, se houver algo de excelente ou digno de louvor, pensem nessas coisas.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29452, 9, "Tudo o que vocês aprenderam, receberam, ouviram e viram em mim, ponham-no em prática. E o Deus da paz estará com vocês.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29453, 10, "Alegro-me grandemente no Senhor, porque finalmente vocês renovaram o seu interesse por mim. De fato, vocês já se interessavam, mas não tinham oportunidade para demonstrá-lo.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29454, 11, "Não estou dizendo isso porque esteja necessitado, pois aprendi a adaptar-me a toda e qualquer circunstância.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29455, 12, "Sei o que é passar necessidade e sei o que é ter fartura. Aprendi o segredo de viver contente em toda e qualquer situação, seja bem alimentado, seja com fome, tendo muito, ou passando necessidade.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29456, 13, "Tudo posso naquele que me fortalece.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29457, 14, "Apesar disso, vocês fizeram bem em participar de minhas tribulações.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29458, 15, "Como vocês sabem, filipenses, nos seus primeiros dias no evangelho, quando parti da Macedônia, nenhuma igreja partilhou comigo no que se refere a dar e receber, exceto vocês;", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29459, 16, "pois, estando eu em Tessalônica, vocês me mandaram ajuda, não apenas uma vez, mas duas, quando tive necessidade.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29460, 17, "Não que eu esteja procurando ofertas, mas o que pode ser creditado na conta de vocês.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29461, 18, "Recebi tudo, e o que tenho é mais que suficiente. Estou amplamente suprido, agora que recebi de Epafrodito os donativos que vocês enviaram. Elas são uma oferta de aroma suave, um sacrifício aceitável e agradável a Deus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29462, 19, "O meu Deus suprirá todas as necessidades de vocês, de acordo com as suas gloriosas riquezas em Cristo Jesus.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29463, 20, "A nosso Deus e Pai seja a glória para todo o sempre. Amém.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29464, 21, "Saúdem a todos os santos em Cristo Jesus. Os irmãos que estão comigo enviam saudações.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29465, 22, "Todos os santos lhes enviam saudações, especialmente os que estão no palácio de César.", 49);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29466, 23, "A graça do Senhor Jesus Cristo seja com o espírito de vocês. Amém.", 49);