INSERT INTO verses (id, number, text, chapter_id) VALUES (29059, 1, "Paulo, apóstolo enviado, não da parte de homens nem por meio de pessoa alguma, mas por Jesus Cristo e por Deus Pai, que o ressuscitou dos mortos,", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29060, 2, "e todos os irmãos que estão comigo, às igrejas da Galácia:", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29061, 3, "A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo,", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29062, 4, "que se entregou a si mesmo por nossos pecados a fim de nos resgatar desta presente era perversa, segundo a vontade de nosso Deus e Pai,", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29063, 5, "a quem seja a glória para todo o sempre. Amém.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29064, 6, "Admiro-me de que vocês estejam abandonando tão rapidamente aquele que os chamou pela graça de Cristo, para seguirem outro evangelho", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29065, 7, "que, na realidade, não é o evangelho. O que ocorre é que algumas pessoas os estão perturbando, querendo perverter o evangelho de Cristo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29066, 8, "Mas ainda que nós ou um anjo do céu pregue um evangelho diferente daquele que lhes pregamos, que seja amaldiçoado!", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29067, 9, "Como já dissemos, agora repito: Se alguém lhes anuncia um evangelho diferente daquele que já receberam, que seja amaldiçoado!", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29068, 10, "Acaso busco eu agora a aprovação dos homens ou a de Deus? Ou estou tentando agradar a homens? Se eu ainda estivesse procurando agradar a homens, não seria servo de Cristo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29069, 11, "Irmãos, quero que saibam que o evangelho por mim anunciado não é de origem humana.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29070, 12, "Não o recebi de pessoa alguma nem me foi ele ensinado; pelo contrário, eu o recebi de Jesus Cristo por revelação.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29071, 13, "Vocês ouviram qual foi o meu procedimento no judaísmo, como perseguia com violência a igreja de Deus, procurando destruí-la.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29072, 14, "No judaísmo, eu superava a maioria dos judeus da minha idade, e era extremamente zeloso das tradições dos meus antepassados.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29073, 15, "Mas Deus me separou desde o ventre materno e me chamou por sua graça. Quando lhe agradou", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29074, 16, "revelar o seu Filho em mim para que eu o anunciasse entre os gentios, não consultei pessoa alguma.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29075, 17, "Tampouco subi a Jerusalém para ver os que já eram apóstolos antes de mim, mas de imediato parti para a Arábia, e tornei a voltar a Damasco.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29076, 18, "Depois de três anos, subi a Jerusalém para conhecer Pedro pessoalmente, e estive com ele quinze dias.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29077, 19, "Não vi nenhum dos outros apóstolos, a não ser Tiago, irmão do Senhor.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29078, 20, "Quanto ao que lhes escrevo, afirmo diante de Deus que não minto.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29079, 21, "A seguir, fui para as regiões da Síria e da Cilícia.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29080, 22, "Eu não era pessoalmente conhecido pelas igrejas da Judéia que estão em Cristo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29081, 23, "Apenas ouviam dizer: ""Aquele que antes nos perseguia, agora está anunciando a fé que outrora procurava destruir"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29082, 24, "E glorificavam a Deus por minha causa.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29083, 1, "Catorze anos depois, subi novamente a Jerusalém, dessa vez com Barnabé, levando também Tito comigo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29084, 2, "Fui para lá por causa de uma revelação e expus diante deles o evangelho que prego entre os gentios, fazendo-o, porém, em particular aos que pareciam mais influentes, para não correr ou ter corrido em vão.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29085, 3, "Mas nem mesmo Tito, que estava comigo, foi obrigado a circuncidar-se, apesar de ser grego.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29086, 4, "Essa questão foi levantada porque alguns falsos irmãos infiltraram-se em nosso meio para espionar a liberdade que temos em Cristo Jesus e nos reduzir à escravidão.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29087, 5, "Não nos submetemos a eles nem por um instante, para que a verdade do evangelho permanecesse com vocês.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29088, 6, "Quanto aos que pareciam influentes — o que eram então não faz diferença para mim; Deus não julga pela aparência — tais homens influentes não me acrescentaram nada.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29089, 7, "Pelo contrário, reconheceram que a mim havia sido confiada a pregação do evangelho aos incircuncisos, assim como a Pedro, aos circuncisos.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29090, 8, "Pois Deus, que operou por meio de Pedro como apóstolo aos circuncisos, também operou por meu intermédio para com os gentios.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29091, 9, "Reconhecendo a graça que me fora concedida, Tiago, Pedro e João, tidos como colunas, estenderam a mão direita a mim e a Barnabé em sinal de comunhão. Eles concordaram em que devíamos nos dirigir aos gentios, e eles, aos circuncisos.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29092, 10, "Somente pediram que nos lembrássemos dos pobres, o que me esforcei por fazer.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29093, 11, "Quando, porém, Pedro veio a Antioquia, enfrentei-o face a face, por sua atitude condenável.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29094, 12, "Pois, antes de chegarem alguns da parte de Tiago, ele comia com os gentios. Quando, porém, eles chegaram, afastou-se e separou-se dos gentios, temendo os que eram da circuncisão.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29095, 13, "Os demais judeus também se uniram a ele nessa hipocrisia, de modo que até Barnabé se deixou levar.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29096, 14, "Quando vi que não estavam andando de acordo com a verdade do evangelho, declarei a Pedro, diante de todos: ""Você é judeu, mas vive como gentio e não como judeu. Portanto, como pode obrigar gentios a viverem como judeus?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29097, 15, """Nós, judeus de nascimento e não ‘gentios pecadores’,", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29098, 16, "sabemos que o ninguém é justificado pela prática da lei, mas mediante a fé em Jesus Cristo. Assim, nós também cremos em Cristo Jesus para sermos justificados pela fé em Cristo, e não pela prática da lei, porque pela prática da lei ninguém será justificado.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29099, 17, """Se, porém, procurando ser justificados em Cristo descobrimos que nós mesmos somos pecadores, será Cristo então ministro do pecado? De modo algum!", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29100, 18, "Se reconstruo o que destruí, provo que sou transgressor.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29101, 19, "Pois, por meio da lei eu morri para a lei, a fim de viver para Deus.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29102, 20, "Fui crucificado com Cristo. Assim, já não sou eu quem vive, mas Cristo vive em mim. A vida que agora vivo no corpo, vivo-a pela fé no filho de Deus, que me amou e se entregou por mim.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29103, 21, "Não anulo a graça de Deus; pois, se a justiça vem pela lei, Cristo morreu inutilmente! """, 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29104, 1, "Ó gálatas insensatos! Quem os enfeitiçou? Não foi diante dos seus olhos que Jesus Cristo foi exposto como crucificado?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29105, 2, "Gostaria de saber apenas uma coisa: foi pela prática da lei que vocês receberam o Espírito, ou pela fé naquilo que ouviram?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29106, 3, "Será que vocês são tão insensatos que, tendo começado pelo Espírito, querem agora se aperfeiçoar pelo esforço próprio?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29107, 4, "Será que foi inútil sofrerem tantas coisas? Se é que foi inútil!", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29108, 5, "Aquele que lhes dá o seu Espírito e opera milagres entre vocês, realiza essas coisas pela prática da lei ou pela fé com a qual receberam a palavra?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29109, 6, "Considerem o exemplo de Abraão: ""Ele creu em Deus, e isso lhe foi creditado como justiça"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29110, 7, "Estejam certos, portanto, de que os que são da fé, estes é que são filhos de Abraão.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29111, 8, "Prevendo a Escritura que Deus justificaria pela fé os gentios, anunciou primeiro as boas novas a Abraão: ""Por meio de você todas as nações serão abençoadas"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29112, 9, "Assim, os que são da fé são abençoados juntamente com Abraão, homem de fé.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29113, 10, "Já os que são pela prática da lei estão debaixo de maldição, pois está escrito: ""Maldito todo aquele que não persiste em praticar todas as coisas escritas no livro da Lei"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29114, 11, "É evidente que diante de Deus ninguém é justificado pela lei, pois ""o justo viverá pela fé"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29115, 12, "A lei não é baseada na fé; pelo contrário, ""quem praticar estas coisas, por elas viverá"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29116, 13, "Cristo nos redimiu da maldição da lei quando se tornou maldição em nosso lugar, pois está escrito: ""Maldito todo aquele que for pendurado num madeiro"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29117, 14, "Isso para que em Cristo Jesus a bênção de Abraão chegasse também aos gentios, para que recebêssemos a promessa do Espírito mediante a fé.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29118, 15, "Irmãos, humanamente falando, ninguém pode anular um testamento depois de ratificado, nem acrescentar-lhe algo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29119, 16, "Assim também as promessas foram feitas a Abraão e ao seu descendente. A Escritura não diz: ""E aos seus descendentes"", como se falando de muitos, mas: ""Ao seu descendente"", dando a entender que se trata de um só, isto é, Cristo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29120, 17, "Quero dizer isto: A lei, que veio quatrocentos e trinta anos depois, não anula a aliança previamente estabelecida por Deus, de modo que venha a invalidar a promessa.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29121, 18, "Pois, se a herança depende da lei, já não depende de promessa. Deus, porém, concedeu-a gratuitamente a Abraão mediante promessa.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29122, 19, "Qual era então o propósito da lei? Foi acrescentada por causa das transgressões, até que viesse o Descendente a quem se referia a promessa, e foi promulgada por meio de anjos, pela mão de um mediador.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29123, 20, "Contudo, o mediador representa mais de um; Deus, porém, é um.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29124, 21, "Então, a lei opõe-se às promessas de Deus? De maneira nenhuma! Pois, se tivesse sido dada uma lei que pudesse conceder vida, certamente a justiça viria da lei.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29125, 22, "Mas a Escritura encerrou tudo debaixo do pecado, a fim de que a promessa, que é pela fé em Jesus Cristo, fosse dada aos que crêem.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29126, 23, "Antes que viesse esta fé, estávamos sob a custódia da lei, nela encerrados, até que a fé que haveria de vir fosse revelada.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29127, 24, "Assim, a lei foi o nosso tutor até Cristo, para que fôssemos justificados pela fé.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29128, 25, "Agora, porém, tendo chegado a fé, já não estamos mais sob o controle do tutor.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29129, 26, "Todos vocês são filhos de Deus mediante a fé em Cristo Jesus,", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29130, 27, "pois os que em Cristo foram batizados, de Cristo se revestiram.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29131, 28, "Não há judeu nem grego, escravo nem livre, homem nem mulher; pois todos são um em Cristo Jesus.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29132, 29, "E, se vocês são de Cristo, são descendência de Abraão e herdeiros segundo a promessa.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29133, 1, "Digo porém que, enquanto o herdeiro é menor de idade, em nada difere de um escravo, embora seja dono de tudo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29134, 2, "No entanto, ele está sujeito a guardiães e administradores até o tempo determinado por seu pai.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29135, 3, "Assim também nós, quando éramos menores, estávamos escravizados aos princípios elementares do mundo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29136, 4, "Mas, quando chegou a plenitude do tempo, Deus enviou seu Filho, nascido de mulher, nascido debaixo da lei,", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29137, 5, "a fim de redimir os que estavam sob a lei, para que recebêssemos a adoção de filhos.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29138, 6, "E, porque vocês são filhos, Deus enviou o Espírito de seu Filho aos seus corações, o qual clama: ""Aba, Pai"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29139, 7, "Assim, você já não é mais escravo, mas filho; e, por ser filho, Deus também o tornou herdeiro.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29140, 8, "Antes, quando vocês não conheciam a Deus, eram escravos daqueles que, por natureza, não são deuses.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29141, 9, "Mas agora, conhecendo a Deus, ou melhor, sendo por ele conhecidos, como é que estão voltando àqueles mesmos princípios elementares, fracos e sem poder? Querem ser escravizados por eles outra vez?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29142, 10, "Vocês estão observando dias especiais, meses, ocasiões específicas e anos!", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29143, 11, "Temo que os meus esforços por vocês tenham sido inúteis.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29144, 12, "Eu lhes suplico, irmãos, que se tornem como eu, pois eu me tornei como vocês. Em nada vocês me ofenderam;", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29145, 13, "como sabem, foi por causa de uma doença que lhes preguei o evangelho pela primeira vez.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29146, 14, "Embora a minha doença lhes tenha sido uma provação, vocês não me trataram com desprezo ou desdém; pelo contrário, receberam-me como se eu fosse um anjo de Deus, como o próprio Cristo Jesus.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29147, 15, "Que aconteceu com a alegria de vocês? Tenho certeza que, se fosse possível, vocês teriam arrancado os próprios olhos para dá-los a mim.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29148, 16, "Tornei-me inimigo de vocês por lhes dizer a verdade?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29149, 17, "Os que fazem tanto esforço para agradá-los, não agem bem, mas querem isolá-los a fim de que vocês também mostrem zelo por eles.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29150, 18, "É bom sempre ser zeloso pelo bem, e não apenas quando estou presente.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29151, 19, "Meus filhos, novamente estou sofrendo dores de parto por sua causa, até que Cristo seja formado em vocês.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29152, 20, "Eu gostaria de estar com vocês agora e mudar o meu tom de voz, pois estou perplexo quanto a vocês.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29153, 21, "Digam-me vocês, os que querem estar debaixo da lei: Acaso vocês não ouvem a lei?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29154, 22, "Pois está escrito que Abraão teve dois filhos, um da escrava e outro da livre.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29155, 23, "O filho da escrava nasceu de modo natural, mas o filho da livre nasceu mediante promessa.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29156, 24, "Isso é usado aqui como uma ilustração; estas mulheres representam duas alianças. Uma aliança procede do monte Sinai e gera filhos para a escravidão: esta é Hagar.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29157, 25, "Hagar representa o monte Sinai, na Arábia, e corresponde à atual cidade de Jerusalém, que está escravizada com os seus filhos.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29158, 26, "Mas a Jerusalém do alto é livre, e essa é a nossa mãe.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29159, 27, "Pois está escrito: ""Regozije-se, ó estéril, você que nunca teve um filho; grite de alegria, você que nunca esteve em trabalho de parto; porque mais são os filhos da mulher abandonada do que os daquela que tem marido"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29160, 28, "Vocês, irmãos, são filhos da promessa, como Isaque.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29161, 29, "Naquele tempo, o filho nascido de modo natural perseguia o filho nascido segundo o Espírito. O mesmo acontece agora.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29162, 30, "Mas o que diz a Escritura? ""Mande embora a escrava e o seu filho, porque o filho da escrava jamais será herdeiro com o filho da livre"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29163, 31, "Portanto, irmãos, não somos filhos da escrava, mas da livre.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29164, 1, "Foi para a liberdade que Cristo nos libertou. Portanto, permaneçam firmes e não se deixem submeter novamente a um jugo de escravidão.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29165, 2, "Ouçam bem o que eu, Paulo, lhes digo: Caso se deixem circuncidar, Cristo de nada lhes servirá.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29166, 3, "De novo declaro a todo homem que se deixa circuncidar que está obrigado a cumprir toda a lei.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29167, 4, "Vocês, que procuram ser justificados pela lei, separaram-se de Cristo; caíram da graça.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29168, 5, "Pois é mediante o Espírito que nós aguardamos pela fé a justiça que é a nossa esperança.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29169, 6, "Porque em Cristo Jesus nem circuncisão nem incircuncisão têm efeito algum, mas sim a fé que atua pelo amor.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29170, 7, "Vocês corriam bem. Quem os impediu de continuar obedecendo à verdade?", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29171, 8, "Tal persuasão não provém daquele que os chama.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29172, 9, """Um pouco de fermento leveda toda a massa"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29173, 10, "Estou convencido no Senhor de que vocês não pensarão de nenhum outro modo. Aquele que os perturba, seja quem for, sofrerá a condenação.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29174, 11, "Irmãos, se ainda estou pregando a circuncisão, por que continuo sendo perseguido? Nesse caso, o escândalo da cruz foi removido.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29175, 12, "Quanto a esses que os perturbam, quem dera que se castrassem!", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29176, 13, "Irmãos, vocês foram chamados para a liberdade. Mas não usem a liberdade para dar ocasião à vontade da carne; pelo contrário, sirvam uns aos outros mediante o amor.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29177, 14, "Toda a lei se resume num só mandamento: ""Ame o seu próximo como a si mesmo"".", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29178, 15, "Mas se vocês se mordem e se devoram uns aos outros, cuidado para não se destruírem mutuamente.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29179, 16, "Por isso digo: vivam pelo Espírito, e de modo nenhum satisfarão os desejos da carne.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29180, 17, "Pois a carne deseja o que é contrário ao Espírito; e o Espírito, o que é contrário à carne. Eles estão em conflito um com o outro, de modo que vocês não fazem o que desejam.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29181, 18, "Mas, se vocês são guiados pelo Espírito, não estão debaixo da lei.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29182, 19, "Ora, as obras da carne são manifestas: imoralidade sexual, impureza e libertinagem;", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29183, 20, "idolatria e feitiçaria; ódio, discórdia, ciúmes, ira, egoísmo, dissensões, facções", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29184, 21, "e inveja; embriaguez, orgias e coisas semelhantes. Eu os advirto, como antes já os adverti, que os que praticam essas coisas não herdarão o Reino de Deus.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29185, 22, "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade,", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29186, 23, "mansidão e domínio próprio. Contra essas coisas não há lei.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29187, 24, "Os que pertencem a Cristo Jesus crucificaram a carne, com as suas paixões e os seus desejos.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29188, 25, "Se vivemos pelo Espírito, andemos também pelo Espírito.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29189, 26, "Não sejamos presunçosos, provocando uns aos outros e tendo inveja uns dos outros.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29190, 1, "Irmãos, se alguém for surpreendido em algum pecado, vocês, que são espirituais deverão restaurá-lo com mansidão. Cuide-se, porém, cada um para que também não seja tentado.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29191, 2, "Levem os fardos pesados uns dos outros e, assim, cumpram a lei de Cristo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29192, 3, "Se alguém se considera alguma coisa, não sendo nada, engana-se a si mesmo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29193, 4, "Cada um examine os próprios atos, e então poderá orgulhar-se de si mesmo, sem se comparar com ninguém,", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29194, 5, "pois cada um deverá levar a própria carga.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29195, 6, "O que está sendo instruído na palavra partilhe todas as coisas boas com quem o instrui.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29196, 7, "Não se deixem enganar: de Deus não se zomba. Pois o que o homem semear, isso também colherá.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29197, 8, "Quem semeia para a sua carne, da carne colherá destruição; mas quem semeia para o Espírito, do Espírito colherá a vida eterna.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29198, 9, "E não nos cansemos de fazer o bem, pois no tempo próprio colheremos, se não desanimarmos.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29199, 10, "Portanto, enquanto temos oportunidade, façamos o bem a todos, especialmente aos da família da fé.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29200, 11, "Vejam com que letras grandes estou lhes escrevendo de próprio punho!", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29201, 12, "Os que desejam causar boa impressão exteriormente, tentando obrigá-los a se circuncidarem, agem desse modo apenas para não serem perseguidos por causa da cruz de Cristo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29202, 13, "Nem mesmo os que são circuncidados cumprem a lei; querem, no entanto, que vocês sejam circuncidados a fim de se gloriarem no corpo de vocês.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29203, 14, "Quanto a mim, que eu jamais me glorie, a não ser na cruz de nosso Senhor Jesus Cristo, por meio da qual o mundo foi crucificado para mim, e eu para o mundo.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29204, 15, "De nada vale ser circuncidado ou não. O que importa é ser uma nova criação.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29205, 16, "Paz e misericórdia estejam sobre todos os que andam conforme essa regra, e também sobre o Israel de Deus.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29206, 17, "Sem mais, que ninguém me perturbe, pois trago em meu corpo as marcas de Jesus.", 47);
INSERT INTO verses (id, number, text, chapter_id) VALUES (29207, 18, "Irmãos, que a graça de nosso Senhor Jesus Cristo seja com o espírito de vocês. Amém.", 47);