INSERT INTO verses (id, number, text, chapter_id) VALUES (20312, 1, "Como está deserta a cidade, antes tão cheia de gente! Como se parece com uma viúva, a que antes era grandiosa entre as nações! A que era a princesa das províncias agora tornou-se uma escrava.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20313, 2, "Chora amargamente à noite, as lágrimas rolam por seu rosto. De todos os seus amantes nenhum a consola. Todos os seus amigos a traíram; tornaram-se seus inimigos.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20314, 3, "Em aflição e sob trabalhos forçados, Judá foi levado ao exílio. Vive entre as nações sem encontrar repouso. Todos os que a perseguiram a capturaram em meio ao seu desespero.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20315, 4, "Os caminhos para Sião pranteiam, porque ninguém comparece às suas festas fixas. Todas as suas portas estão desertas, seus sacerdotes gemem, suas moças se entristecem, e ela se encontra em angústia profunda.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20316, 5, "Seus adversários são os seus chefes; seus inimigos estão tranqüilos. O Senhor lhe trouxe tristeza por causa dos seus muitos pecados. Seus filhos foram levados ao exílio, prisioneiros dos adversários.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20317, 6, "Todo o esplendor fugiu da cidade de Sião. Seus líderes são como corças que não encontram pastagem; sem forças fugiram diante do perseguidor.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20318, 7, "Nos dias de sua aflição e de seu desnorteio Jerusalém se lembra de todos os tesouros que lhe pertenciam nos tempos passados. Quando o seu povo caiu nas mãos do inimigo, ninguém veio ajudá-la. Seus inimigos olharam para ela e zombaram da sua queda.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20319, 8, "Jerusalém cometeu graves pecados; por isso tornou-se impura. Todos os que a honravam agora a desprezam, porque viram a sua nudez; ela mesma geme e se desvia deles.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20320, 9, "Sua impureza prende-se às suas saias; ela não esperava que chegaria o seu fim. Sua queda foi surpreendente; ninguém veio consolá-la. ""Olha, Senhor, para a minha aflição, pois o inimigo triunfou. """, 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20321, 10, "O adversário saqueia todos os seus tesouros; ela viu nações pagãs entrarem em seu santuário, sendo que tu as tinhas proibido de participar das tuas assembléias.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20322, 11, "Todo o seu povo se lamenta enquanto vai em busca de pão; e para sobreviverem, trocam os tesouros por comida. ""Olha, Senhor, e considera, pois tenho sido desprezada. """, 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20323, 12, """Vocês não se comovem, todos vocês que passam por aqui? Olhem ao redor e vejam se há sofrimento maior do que o que me foi imposto e que o Senhor trouxe sobre mim no dia em que se acendeu a sua ira.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20324, 13, "Do alto ele fez cair fogo sobre os meus ossos. Armou uma rede para os meus pés e me derrubou de costas. Deixou-me desolada, desfalecida o dia todo.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20325, 14, "Os meus pecados foram amarrados num jugo; suas mãos os ataram todos juntos, e os colocaram em meu pescoço; o Senhor abateu a minha força. Ele me entregou àqueles que não consigo vencer.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20326, 15, "O Senhor dispersou todos os guerreiros que me apoiavam; convocou um exército contra mim para destruir os meus jovens. O Senhor pisou no seu lagar a virgem, a cidade de Judá.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20327, 16, "É por isso que eu choro; as lágrimas inundam os meus olhos. Ninguém está por perto para consolar-me, não há ninguém que restaure o meu espírito. Meus filhos estão desamparados porque o inimigo prevaleceu. """, 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20328, 17, "Sião estende as mãos suplicantes mas não há quem a console. O Senhor decretou que os vizinhos de Jacó se tornem seus adversários; Jerusalém tornou-se coisa imunda entre eles.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20329, 18, """O Senhor é justo, mas eu me rebelei contra a sua ordem. Ouçam, todos os povos; olhem para o meu sofrimento. Meus jovens e minhas moças foram para o exílio.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20330, 19, "Chamei os meus aliados, mas eles me traíram. Meus sacerdotes e meus líderes pereceram na cidade, enquanto procuravam comida para poderem sobreviver.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20331, 20, "Veja, Senhor, como estou angustiada! Estou atormentada no íntimo, e no meu coração me perturbo pois tenho sido muito rebelde. Lá fora, a espada a todos consome; dentro impera a morte.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20332, 21, "Os meus lamentos têm sido ouvidos, mas não há ninguém que me console. Todos os meus inimigos sabem da minha agonia; eles se alegram com o que fizeste. Quem dera trouxesses o dia que anunciaste para que eles ficassem como eu.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20333, 22, "Que toda a maldade deles seja conhecida diante de ti; faze com eles o que fizeste comigo por causa de todos os meus pecados. Os meus gemidos são muitos e o meu coração desfalece. """, 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20334, 1, "O Senhor cobriu a cidade de Sião com a nuvem da sua ira! Lançou por terra o esplendor de Israel, que se elevava para os céus; não se lembrou do estrado dos seus pés no dia da sua ira.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20335, 2, "Sem piedade o Senhor devorou todas as habitações de Jacó; em sua ira destruiu as fortalezas da filha de Judá. Derrubou ao chão e desonrou o seu reino e os seus líderes.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20336, 3, "No acender da sua ira cortou todo o poder de Israel. Retirou a sua mão direita diante da aproximação do inimigo. Queimou Jacó como um fogo ardente que consome tudo ao redor.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20337, 4, "Como um inimigo, preparou o seu arco; como um adversário, a sua mão direita está pronta. Ele massacrou tudo o que era agradável contemplar; derramou sua ira como fogo sobre a tenda da cidade de Sião.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20338, 5, "O Senhor é como um inimigo; ele tem devorado Israel. Tem devorado todos os seus palácios e destruído as suas fortalezas. Tem feito multiplicar os prantos e as lamentações da filha de Judá.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20339, 6, "Ele destroçou a sua morada como se fosse um simples jardim; destruiu o seu local de reuniões. O Senhor fez esquecidas em Sião suas festas fixas e seus sábados; em seu grande furor rejeitou o rei e o sacerdote.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20340, 7, "O Senhor rejeitou o seu altar e abandonou o seu santuário. Entregou aos inimigos os muros dos seus palácios, e eles deram gritos na casa do Senhor, como fazíamos nos dias de festa.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20341, 8, "O Senhor está decidido a derrubar os muros da cidade de Sião. Esticou uma trena e não poupou a sua mão destruidora. Fez com que os muros e as paredes se lamentassem; juntos eles se desmoronaram.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20342, 9, "Suas portas caíram por terra; suas trancas ele quebrou e destruiu. O seu rei e os seus líderes foram exilados para diferentes nações, e a lei já não existe; seus profetas já não recebem visões do Senhor.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20343, 10, "Os líderes da cidade de Sião sentam-se no chão em silêncio; despejam pó sobre a cabeça e usam vestes de lamento. As moças de Jerusalém inclinam a cabeça até o chão.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20344, 11, "Meus olhos estão cansados de chorar, minha alma está atormentada, meu coração se derrama, porque o meu povo está destruído, porque crianças e bebês desmaiam pelas ruas da cidade.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20345, 12, """Eles clamam às suas mães: Onde estão o pão e o vinho? "" Ao mesmo tempo em que desmaiam pelas ruas da cidade, como os feridos, e suas vidas se desvanecem nos braços de suas mães.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20346, 13, "Que posso dizer a seu favor? Com que posso compará-la, ó cidade de Jerusalém? Com que posso assemelhá-la, a fim de trazer-lhe consolo, ó virgem, ó cidade de Sião? Sua ferida é tão profunda quanto o oceano; quem pode curá-la?", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20347, 14, "As visões dos seus profetas eram falsas e inúteis; eles não expuseram o seu pecado para evitar o seu cativeiro. As mensagens que eles lhe deram eram falsas e enganosas.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20348, 15, "Todos os que cruzam o seu caminho batem palmas; eles zombam e meneiam a cabeça diante da cidade de Jerusalém: ""É esta a cidade que era chamada, a perfeição da beleza, a alegria de toda a terra? """, 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20349, 16, "Todos os seus inimigos escancaram a boca contra você; eles zombam, rangem os dentes e dizem: ""Nós a devoramos. Este é o dia que esperávamos; pois não é que vivemos até vê-lo chegar? """, 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20350, 17, "O Senhor fez o que planejou; cumpriu a sua palavra, que há muito tinha decretado. Derrubou tudo sem piedade, permitiu que o inimigo zombasse de você, exaltou o poder dos seus adversários.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20351, 18, "O coração do povo clama ao Senhor. Ó muro da cidade de Sião, corram como um rio as suas lágrimas dia e noite; não se permita nenhum descanso nem dê repouso à menina dos seus olhos.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20352, 19, "Levante-se, grite no meio da noite, quando começam as vigílias noturnas; derrame o seu coração como água na presença do Senhor. Levante para ele as mãos em favor da vida de seus filhos, que desmaiam de fome nas esquinas de todas as ruas.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20353, 20, """Olha, Senhor, e considera: A quem o Senhor tratou dessa maneira? Deverão as mulheres comer os próprios filhos, as crianças de quem elas cuidaram? Deverão os profetas e os sacerdotes ser assassinados no santuário do Senhor?", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20354, 21, "Jovens e velhos espalham-se em meio ao pó das ruas; meus jovens e minhas virgens caíram mortos à espada. Tu os sacrificaste no dia da tua ira; tu os mataste sem piedade.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20355, 22, "Como se faz convocação para um dia de festa, convocaste contra mim terrores por todos os lados. No dia da ira do Senhor, ninguém escapou nem sobreviveu; aqueles dos quais eu cuidava e os quais eu fiz crescer, o meu inimigo destruiu. """, 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20356, 1, "Eu sou o homem que viu a aflição trazida pela vara da sua ira.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20357, 2, "Ele me impeliu e me fez andar na escuridão, e não na luz;", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20358, 3, "sim, ele voltou sua mão contra mim vez após vez, o tempo todo.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20359, 4, "Fez que a minha pele e a minha carne envelhecessem e quebrou os meus ossos.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20360, 5, "Ele me sitiou e me cercou de amargura e de pesar.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20361, 6, "Fez-me habitar na escuridão como os que há muito morreram.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20362, 7, "Cercou-me de muros, e não posso escapar; atou-me a pesadas correntes.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20363, 8, "Mesmo quando chamo ou grito por socorro, ele rejeita a minha oração.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20364, 9, "Ele impediu o meu caminho com blocos de pedra; e fez tortuosas as minhas sendas.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20365, 10, "Como um urso à espreita, como um leão escondido,", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20366, 11, "arrancou-me do caminho e despedaçou-me, deixando-me abandonado.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20367, 12, "Preparou o seu arco e me fez alvo de suas flechas.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20368, 13, "Atingiu o meu coração com flechas de sua aljava.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20369, 14, "Tornei-me motivo de riso de todo o meu povo; nas suas canções eles zombam de mim o tempo todo.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20370, 15, "Fez-me comer ervas amargas e fartou-me de fel.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20371, 16, "Quebrou os meus dentes com pedras; e pisoteou-me no pó.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20372, 17, "Tirou-me a paz; esqueci-me do que significa prosperidade.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20373, 18, "Por isso digo: ""Meu esplendor já se foi, bem como tudo o que eu esperava do Senhor"".", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20374, 19, "Lembro-me da minha aflição e do meu delírio, da minha amargura e do meu pesar.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20375, 20, "Lembro-me bem disso tudo, e a minha alma desfalece dentro de mim.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20376, 21, "Todavia, lembro-me também do que pode dar-me esperança:", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20377, 22, "Graças ao grande amor do Senhor é que não somos consumidos, pois as suas misericórdias são inesgotáveis.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20378, 23, "Renovam-se cada manhã; grande é a tua fidelidade!", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20379, 24, "Digo a mim mesmo: A minha porção é o Senhor; portanto, nele porei a minha esperança.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20380, 25, "O Senhor é bom para com aqueles cuja esperança está nele, para com aqueles que o buscam;", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20381, 26, "é bom esperar tranqüilo pela salvação do Senhor.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20382, 27, "É bom que o homem suporte o jugo enquanto é jovem.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20383, 28, "Leve-o sozinho e em silêncio, porque o Senhor o pôs sobre ele.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20384, 29, "Ponha o seu rosto no pó; talvez ainda haja esperança.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20385, 30, "Ofereça o rosto a quem o quer ferir, e engula a desonra.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20386, 31, "Porque o Senhor não o desprezará para sempre.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20387, 32, "Embora ele traga tristeza, mostrará compaixão, tão grande é o seu amor infalível.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20388, 33, "Porque não é do seu agrado trazer aflição e tristeza aos filhos dos homens.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20389, 34, "Esmagar com os pés todos os prisioneiros da terra,", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20390, 35, "negar a alguém os seus direitos, enfrentando o Altíssimo,", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20391, 36, "impedir a alguém o acesso à justiça; não veria o Senhor tais coisas?", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20392, 37, "Quem poderá falar e fazer acontecer, se o Senhor não o tiver decretado?", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20393, 38, "Não é da boca do Altíssimo que vêm tanto as desgraças como as bênçãos?", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20394, 39, "Como pode um homem reclamar quando é punido por seus pecados?", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20395, 40, "Examinemos e submetamos à prova os nossos caminhos, e depois voltemos ao Senhor.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20396, 41, "Levantemos o coração e as mãos para Deus, que está nos céus, e digamos:", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20397, 42, """Pecamos e nos rebelamos, e tu não nos perdoaste.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20398, 43, "Tu te cobriste de ira e nos perseguiste, massacraste-nos sem piedade.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20399, 44, "Tu te escondeste atrás de uma nuvem para que nenhuma oração chegasse a ti.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20400, 45, "Tu nos tornaste escória e refugo entre as nações.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20401, 46, "Todos os nossos inimigos escancaram a boca contra nós.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20402, 47, "Sofremos terror e ciladas, ruína e destruição"".", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20403, 48, "Rios de lágrimas correm dos meus ohos porque o meu povo foi destruído.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20404, 49, "Meus olhos choram sem parar, sem nenhum descanso,", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20405, 50, "até que o Senhor contemple dos céus e veja.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20406, 51, "O que eu enxergo enche-me a alma de tristeza, de pena de todas as mulheres da minha cidade.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20407, 52, "Aqueles que, sem motivo, eram meus inimigos caçaram-me como a um passarinho.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20408, 53, "Procuraram fazer minha vida acabar na cova e me jogaram pedras;", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20409, 54, "as águas me encobriram a cabeça, e cheguei a pensar que o fim de tudo tinha chegado.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20410, 55, "Clamei pelo teu nome, Senhor, das profundezas da cova.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20411, 56, "Tu ouviste o meu clamor: ""Não feches os teus ouvidos aos meus gritos de socorro"".", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20412, 57, "Tu te aproximaste quando a ti clamei, e disseste: ""Não tenha medo"".", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20413, 58, "Senhor, tu assumiste a minha causa; e redimiste a minha vida.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20414, 59, "Tu tens visto, Senhor, o mal que me tem sido feito. Toma a teu cargo a minha causa!", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20415, 60, "Tu viste como é terrível a vingança deles, todas as suas ciladas contra mim.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20416, 61, "Senhor, tu ouviste os seus insultos, todas as suas ciladas contra mim,", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20417, 62, "aquilo que os meus inimigos sussurram e murmuram o tempo todo contra mim.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20418, 63, "Olha para eles! Sentados ou em pé, zombam de mim com as suas canções.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20419, 64, "Dá-lhes o que merecem, Senhor, conforme o que as suas mãos têm feito.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20420, 65, "Coloca um véu sobre os seus corações e esteja a tua maldição sobre eles.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20421, 66, "Persegue-os com fúria e elimina-os de debaixo dos teus céus, ó Senhor.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20422, 1, "Como o ouro perdeu o brilho! Como o ouro fino ficou embaçado! As pedras sagradas estão espalhadas pelas esquinas de todas as ruas.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20423, 2, "Como os preciosos filhos de Sião, que antes valiam seu peso em ouro, hoje são considerados como vasos de barro, obra das mãos de um oleiro!", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20424, 3, "Até os chacais oferecem o peito para amamentar os seus filhotes, mas o meu povo não tem mais coração; é como as avestruzes do deserto.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20425, 4, "De tanta sede, a língua dos bebês gruda no céu da boca; as crianças imploram pelo pão, mas ninguém as atende.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20426, 5, "Aqueles que costumavam comer comidas finas passam necessidades nas ruas. Aqueles que se adornavam de púrpura hoje estão prostrados sobre montes de cinza.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20427, 6, "A punição do meu povo é maior que a de Sodoma, que foi destruída num instante sem que ninguém a socorresse.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20428, 7, "Seus príncipes eram mais brilhantes que a neve e mais brancos do que o leite, tinham a pele mais rosada que rubis; sua aparência lembrava safiras.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20429, 8, "Mas agora estão mais negros do que o carvão; não são reconhecidos nas ruas. Sua pele enrugou-se sobre os seus ossos; parecem agora madeira seca.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20430, 9, "Os que foram mortos pela espada estão melhor do que os que morrem de fome, os quais, torturados pela fome, definham pela falta de produção das lavouras.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20431, 10, "Com as próprias mãos, mulheres bondosas cozinharam os próprios filhos, que se tornaram a sua comida quando o meu povo foi destruído.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20432, 11, "O Senhor deu vazão total à sua ira; derramou a sua grande fúria. Ele acendeu em Sião um fogo que consumiu os seus alicerces.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20433, 12, "Os reis da terra e os povos de todo o mundo, não acreditavam que os inimigos e os adversários pudessem entrar pelas portas de Jerusalém.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20434, 13, "Dentro da cidade foi derramado o sangue dos justos por causa do pecado dos seus profetas e das maldades dos seus sacerdotes.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20435, 14, "Hoje eles tateiam pelas ruas como cegos, e tão sujos de sangue estão, que ninguém ousa tocar em suas vestes.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20436, 15, """Vocês estão imundos! "", o povo grita para eles. ""Afastem-se! Não nos toquem! "" Quando eles fogem e ficam vagando, os povos das outras nações dizem: ""Aqui eles não podem habitar"".", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20437, 16, "O próprio Senhor os espalhou; ele já não cuida deles. Ninguém honra os sacerdotes nem respeita os líderes.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20438, 17, "Nossos olhos estão cansados de buscar ajuda em vão; de nossas torres buscávamos uma nação que não podia salvar-nos.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20439, 18, "Cada passo nosso era vigiado, de forma que não podíamos caminhar por nossas ruas. Nosso fim estava próximo, nossos dias estavam contados; o nosso fim já havia chegado.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20440, 19, "Nossos perseguidores eram mais velozes do que águias nos céus; perseguiam-nos por sobre as montanhas, ficavam de tocaia contra nós no deserto.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20441, 20, "O ungido do Senhor, o próprio fôlego da nossa vida, foi capturado em suas armadilhas. E nós que pensávamos que sob a sua sombra viveríamos entre as nações!", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20442, 21, "Alegre-se e exulte, ó terra de Edom, você que vive na terra de Uz. Mas a você também será servido o cálice: você será embriagada e as suas roupas serão arrancadas.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20443, 22, "Ó cidade de Sião, o seu castigo terminará; o Senhor não prolongará o seu exílio. Mas, ó terra de Edom, ele punirá o seu pecado e porá à mostra a sua perversidade.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20444, 1, "Lembra-te, Senhor, do que tem acontecido conosco; olha e vê a nossa desgraça.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20445, 2, "Nossa herança foi entregue aos estranhos, nossas casas, aos estrangeiros.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20446, 3, "Somos órfãos de pai, nossas mães são viúvas.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20447, 4, "Temos que comprar a água que bebemos; nossa lenha, só conseguimos pagando.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20448, 5, "Aqueles que nos perseguem estão bem próximos; estamos exaustos e não temos como descansar.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20449, 6, "Submetemo-nos ao Egito e à Assíria a fim de conseguirmos pão.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20450, 7, "Nossos pais pecaram e já não existem mais, e nós levamos o castigo pelos seus pecados.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20451, 8, "Escravos dominam sobre nós, e não há quem possa livrar-nos das suas mãos.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20452, 9, "Conseguimos pão arriscando as nossas vidas enfrentando a espada do deserto.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20453, 10, "Nossa pele está quente como um forno, febril de tanta fome.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20454, 11, "As mulheres têm sido violentadas em Sião, e as virgens, nas cidades de Judá.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20455, 12, "Os líderes foram pendurados pelas mãos; aos idosos não se mostra nenhum respeito.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20456, 13, "Os jovens trabalham nos moinhos; os meninos cambaleiam sob o fardo de lenha.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20457, 14, "Os líderes já não se reúnem junto às portas da cidade; os jovens cessaram a sua música.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20458, 15, "Dos nossos corações fugiu a alegria; nossas danças se transformaram em lamentos.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20459, 16, "A coroa caiu da nossa cabeça. Ai de nós, porque temos pecado!", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20460, 17, "E por esse motivo o nosso coração desfalece, e os nossos olhos perdem o brilho.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20461, 18, "Tudo porque o monte Sião está deserto, e os chacais perambulam por ele.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20462, 19, "Tu, Senhor, reinas para sempre; teu trono permanece de geração a geração.", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20463, 20, "Por que motivo então te esquecerias de nós? Por que haverias de desamparar-nos por tanto tempo?", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20464, 21, "Restaura-nos para ti, Senhor, para que voltemos; renova os nossos dias como os de antigamente,", 24);
INSERT INTO verses (id, number, text, chapter_id) VALUES (20465, 22, "a não ser que já nos tenhas rejeitado completamente e a tua ira contra nós não tenha limite!", 24);