INSERT INTO verses (id, number, text, chapter_id) VALUES (27932, 1, "Paulo, servo de Cristo Jesus, chamado para ser apóstolo, separado para o evangelho de Deus,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27933, 2, "o qual foi prometido por ele de antemão por meio dos seus profetas nas Escrituras Sagradas,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27934, 3, "acerca de seu Filho, que, como homem, era descendente de Davi,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27935, 4, "e que mediante o Espírito de santidade foi declarado Filho de Deus com poder, pela sua ressurreição dentre os mortos: Jesus Cristo, nosso Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27936, 5, "Por meio dele e por causa do seu nome, recebemos graça e apostolado para chamar dentre todas as nações um povo para a obediência que vem pela fé.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27937, 6, "E vocês também estão entre os chamados para pertencerem a Jesus Cristo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27938, 7, "A todos os que em Roma são amados de Deus e chamados para serem santos: A vocês, graça e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27939, 8, "Antes de tudo, sou grato a meu Deus, mediante Jesus Cristo, por todos vocês, porque em todo o mundo está sendo anunciada a fé que vocês têm.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27940, 9, "Deus, a quem sirvo de todo o coração pregando o evangelho de seu Filho, é minha testemunha de como sempre me lembro de vocês", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27941, 10, "em minhas orações; e peço que agora, finalmente, pela vontade de Deus, seja-me aberto o caminho para que eu possa visitá-los.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27942, 11, "Anseio vê-los, a fim de compartilhar com vocês algum dom espiritual, para fortalecê-los,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27943, 12, "isto é, para que eu e vocês sejamos mutuamente encorajados pela fé.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27944, 13, "Quero que vocês saibam, irmãos, que muitas vezes planejei visitá-los, mas fui impedido de fazê-lo até agora. Meu propósito é colher algum fruto entre vocês, assim como tenho colhido entre os demais gentios.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27945, 14, "Sou devedor tanto a gregos como a bárbaros, tanto a sábios como a ignorantes.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27946, 15, "Por isso estou disposto a pregar o evangelho também a vocês que estão em Roma.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27947, 16, "Não me envergonho do evangelho, porque é o poder de Deus para a salvação de todo aquele que crê: primeiro do judeu, depois do grego.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27948, 17, "Porque no evangelho é revelada a justiça de Deus, uma justiça que do princípio ao fim é pela fé, como está escrito: ""O justo viverá pela fé"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27949, 18, "Portanto, a ira de Deus é revelada do céu contra toda impiedade e injustiça dos homens que suprimem a verdade pela injustiça,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27950, 19, "pois o que de Deus se pode conhecer é manifesto entre eles, porque Deus lhes manifestou.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27951, 20, "Pois desde a criação do mundo os atributos invisíveis de Deus, seu eterno poder e sua natureza divina, têm sido vistos claramente, sendo compreendidos por meio das coisas criadas, de forma que tais homens são indesculpáveis;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27952, 21, "porque, tendo conhecido a Deus, não o glorificaram como Deus, nem lhe renderam graças, mas os seus pensamentos tornaram-se fúteis e os seus corações insensatos se obscureceram.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27953, 22, "Dizendo-se sábios, tornaram-se loucos", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27954, 23, "e trocaram a glória do Deus imortal por imagens feitas segundo a semelhança do homem mortal, bem como de pássaros, quadrúpedes e répteis.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27955, 24, "Por isso Deus os entregou à impureza sexual, segundo os desejos pecaminosos dos seus corações, para a degradação dos seus corpos entre si.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27956, 25, "Trocaram a verdade de Deus pela mentira, e adoraram e serviram a coisas e seres criados, em lugar do Criador, que é bendito para sempre. Amém.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27957, 26, "Por causa disso Deus os entregou a paixões vergonhosas. Até suas mulheres trocaram suas relações sexuais naturais por outras, contrárias à natureza.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27958, 27, "Da mesma forma, os homens também abandonaram as relações naturais com as mulheres e se inflamaram de paixão uns pelos outros. Começaram a cometer atos indecentes, homens com homens, e receberam em si mesmos o castigo merecido pela sua perversão.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27959, 28, "Além do mais, visto que desprezaram o conhecimento de Deus, ele os entregou a uma disposição mental reprovável, para praticarem o que não deviam.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27960, 29, "Tornaram-se cheios de toda sorte de injustiça, maldade, ganância e depravação. Estão cheios de inveja, homicídio, rivalidades, engano e malícia. São bisbilhoteiros,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27961, 30, "caluniadores, inimigos de Deus, insolentes, arrogantes e presunçosos; inventam maneiras de praticar o mal; desobedecem a seus pais;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27962, 31, "são insensatos, desleais, sem amor pela família, implacáveis.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27963, 32, "Embora conheçam o justo decreto de Deus, de que as pessoas que praticam tais coisas merecem a morte, não somente continuam a praticá-las, mas também aprovam aqueles que as praticam.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27964, 1, "Portanto, você, que julga, os outros é indesculpável; pois está condenando a si mesmo naquilo em que julga, visto que você, que julga, pratica as mesmas coisas.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27965, 2, "Sabemos que o juízo de Deus contra os que praticam tais coisas é conforme a verdade.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27966, 3, "Assim, quando você, um simples homem, os julga, mas pratica as mesmas coisas, pensa que escapará do juízo de Deus?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27967, 4, "Ou será que você despreza as riquezas da sua bondade, tolerância e paciência, não reconhecendo que a bondade de Deus o leva ao arrependimento?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27968, 5, "Contudo, por causa da sua teimosia e do seu coração obstinado, você está acumulando ira contra si mesmo, para o dia da ira de Deus, quando se revelará o seu justo julgamento.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27969, 6, "Deus ""retribuirá a cada um conforme o seu procedimento"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27970, 7, "Ele dará vida eterna aos que, persistindo em fazer o bem, buscam glória, honra e imortalidade.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27971, 8, "Mas haverá ira e indignação para os que são egoístas, que rejeitam a verdade e seguem a injustiça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27972, 9, "Haverá tribulação e angústia para todo ser humano que pratica o mal: primeiro para o judeu, depois para o grego;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27973, 10, "mas glória, honra e paz para todo o que pratica o bem: primeiro para o judeu, depois para o grego.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27974, 11, "Pois em Deus não há parcialidade.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27975, 12, "Todo aquele que pecar sem a lei, sem a lei também perecerá, e todo aquele que pecar sob a lei, pela lei será julgado.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27976, 13, "Porque não são os que ouvem a Lei que são justos aos olhos de Deus; mas os que obedecem à lei, estes serão declarados justos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27977, 14, "( De fato, quando os gentios, que não têm a lei, praticam naturalmente o que ela ordena, tornam-se lei para si mesmos, embora não possuam a lei;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27978, 15, "pois mostram que as exigências da lei estão gravadas em seus corações. Disso dão testemunho também a consciência e os pensamentos deles, ora acusando-os, ora defendendo-os. )", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27979, 16, "Isso acontecerá no dia em que Deus julgar os segredos dos homens, mediante Jesus Cristo, conforme o declara o meu evangelho.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27980, 17, "Ora, você que leva o nome de judeu, apóia-se na lei e orgulha-se em Deus;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27981, 18, "se você conhece a vontade de Deus e aprova o que é superior, porque é instruído pela lei;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27982, 19, "se está convencido de que é guia de cegos, luz para os que estão em trevas,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27983, 20, "instrutor de insensatos, mestre de crianças, porque tem na lei a expressão do conhecimento e da verdade;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27984, 21, "então você, que ensina os outros, não ensina a si mesmo? Você, que prega contra o furto, furta?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27985, 22, "Você, que diz que não se deve adulterar, adultera? Você, que detesta ídolos, rouba-lhes os templos?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27986, 23, "Você, que se orgulha na lei, desonra a Deus, desobedecendo à lei?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27987, 24, "Como está escrito: ""O nome de Deus é blasfemado entre os gentios por causa de vocês"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27988, 25, "A circuncisão tem valor se você obedece à lei; mas, se você desobedece à lei, a sua circuncisão já se tornou incircuncisão.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27989, 26, "Se aqueles que não são circuncidados obedecem aos preceitos da lei, não serão eles considerados circuncidados?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27990, 27, "Aquele que não é circuncidado fisicamente, mas obedece à lei, condenará você que, tendo a lei escrita e a circuncisão, é transgressor da lei.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27991, 28, "Não é judeu quem o é apenas exteriormente, nem é circuncisão a que é meramente exterior e física.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27992, 29, "Não! Judeu é quem o é interiormente, e circuncisão é a operada no coração, pelo Espírito, e não pela lei escrita. Para estes o louvor não provém dos homens, mas de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27993, 1, "Que vantagem há então em ser judeu, ou que utilidade há na circuncisão?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27994, 2, "Muita, em todos os sentidos! Principalmente porque aos judeus foram confiadas as palavras de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27995, 3, "Que importa se alguns deles foram infiéis? A sua infidelidade anulará a fidelidade de Deus?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27996, 4, "De maneira nenhuma! Seja Deus verdadeiro, e todo homem mentiroso. Como está escrito: ""De modo que são justas as tuas palavras e prevaleces quando julgas"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27997, 5, "Mas, se a nossa injustiça ressalta de maneira ainda mais clara a justiça de Deus, que diremos? Que Deus é injusto por aplicar a sua ira? ( Estou usando um argumento humano. )", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27998, 6, "Claro que não! Se fosse assim, como Deus iria julgar o mundo?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (27999, 7, "Alguém pode alegar ainda: ""Se a minha mentira ressalta a veracidade de Deus, aumentando assim a sua glória, por que sou condenado como pecador? """, 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28000, 8, "Por que não dizer como alguns caluniosamente afirmam que dizemos: ""Façamos o mal, para que nos venha o bem""? A condenação dos tais é merecida.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28001, 9, "Que concluiremos então? Estamos em posição de vantagem? Não! Já demonstramos que tanto judeus quanto gentios estão debaixo do pecado.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28002, 10, "Como está escrito: ""Não há nenhum justo, nem um sequer;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28003, 11, "não há ninguém que entenda, ninguém que busque a Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28004, 12, "Todos se desviaram, tornaram-se juntamente inúteis; não há ninguém que faça o bem, não há nem um sequer"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28005, 13, """Suas gargantas são um túmulo aberto; com suas línguas enganam"". ""Veneno de serpentes está em seus lábios"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28006, 14, """Suas bocas estão cheias de maldição e amargura"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28007, 15, """Seus pés são ágeis para derramar sangue;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28008, 16, "ruína e desgraça marcam os seus caminhos,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28009, 17, "e não conhecem o caminho da paz"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28010, 18, """Aos seus olhos é inútil temer a Deus"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28011, 19, "Sabemos que tudo o que a lei diz, o diz àqueles que estão debaixo dela, para que toda boca se cale e todo o mundo esteja sob o juízo de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28012, 20, "Portanto, ninguém será declarado justo diante dele baseando-se na obediência à lei, pois é mediante a lei que nos tornamos plenamente conscientes do pecado.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28013, 21, "Mas agora se manifestou uma justiça que provém de Deus, independente da lei, da qual testemunham a Lei e os Profetas,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28014, 22, "justiça de Deus mediante a fé em Jesus Cristo para todos os que crêem. Não há distinção,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28015, 23, "pois todos pecaram e estão destituídos da glória de Deus,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28016, 24, "sendo justificados gratuitamente por sua graça, por meio da redenção que há em Cristo Jesus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28017, 25, "Deus o ofereceu como sacrifício para propiciação mediante a fé, pelo seu sangue, demonstrando a sua justiça. Em sua tolerância, havia deixado impunes os pecados anteriormente cometidos;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28018, 26, "mas, no presente, demonstrou a sua justiça, a fim de ser justo e justificador daquele que tem fé em Jesus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28019, 27, "Onde está, então, o motivo de vanglória? É excluído. Baseado em que princípio? No da obediência à lei? Não, mas no princípio da fé.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28020, 28, "Pois sustentamos que o homem é justificado pela fé, independente da obediência à lei.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28021, 29, "Deus é Deus apenas dos judeus? Ele não é também o Deus dos gentios? Sim, dos gentios também,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28022, 30, "visto que existe um só Deus, que pela fé justificará os circuncisos e os incircuncisos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28023, 31, "Anulamos então a lei pela fé? De maneira nenhuma! Pelo contrário, confirmamos a lei.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28024, 1, "Portanto, que diremos do nosso antepassado Abraão?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28025, 2, "Se de fato Abraão foi justificado pelas obras, ele tem do que se gloriar, mas não diante de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28026, 3, "Que diz a Escritura? ""Abraão creu em Deus, e isso lhe foi creditado como justiça"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28027, 4, "Ora, o salário do homem que trabalha não é considerado como favor, mas como dívida.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28028, 5, "Todavia, àquele que não trabalha, mas confia em Deus que justifica o ímpio, sua fé lhe é creditada como justiça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28029, 6, "Davi diz a mesma coisa, quando fala da felicidade do homem a quem Deus credita justiça independente de obras:", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28030, 7, """Como são felizes aqueles que têm suas transgressões perdoadas, cujos pecados são apagados.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28031, 8, "Como é feliz aquele a quem o Senhor não atribui culpa"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28032, 9, "Destina-se esta felicidade apenas aos circuncisos ou também aos incircuncisos? Já dissemos que, no caso de Abraão, a fé lhe foi creditada como justiça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28033, 10, "Sob quais circunstâncias? Antes ou depois de ter sido circuncidado? Não foi depois, mas antes!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28034, 11, "Assim ele recebeu a circuncisão como sinal, como selo da justiça que ele tinha pela fé, quando ainda não fora circuncidado. Portanto, ele é o pai de todos os que crêem, sem terem sido circuncidados, a fim de que a justiça fosse creditada também a eles;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28035, 12, "e é igualmente o pai dos circuncisos que não somente são circuncisos, mas também andam nos passos da fé que teve nosso pai Abraão antes de passar pela circuncisão.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28036, 13, "Não foi mediante a lei que Abraão e a sua descendência receberam a promessa de que ele seria o herdeiro do mundo, mas mediante a justiça que vem da fé.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28037, 14, "Pois se os que vivem pela lei são herdeiros, a fé não tem valor, e a promessa é inútil;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28038, 15, "porque a lei produz a ira. E onde não há lei, não há transgressão.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28039, 16, "Portanto, a promessa vem pela fé, para que seja de acordo com a graça e seja assim garantida a toda a descendência de Abraão; não apenas aos que estão sob o regime da lei, mas também aos que têm a fé que Abraão teve. Ele é o pai de todos nós.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28040, 17, "Como está escrito: ""Eu o constituí pai de muitas nações"". Ele é nosso pai aos olhos de Deus, em quem creu, o Deus que dá vida aos mortos e chama à existência coisas que não existem, como se existissem.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28041, 18, "Abraão, contra toda esperança, em esperança creu, tornando-se assim pai de muitas nações, como foi dito a seu respeito: ""Assim será a sua descendência"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28042, 19, "Sem se enfraquecer na fé, reconheceu que o seu corpo já estava sem vitalidade, pois já contava cerca de cem anos de idade, e que também o ventre de Sara já estava sem vitalidade.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28043, 20, "Mesmo assim não duvidou nem foi incrédulo em relação à promessa de Deus, mas foi fortalecido em sua fé e deu glória a Deus,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28044, 21, "estando plenamente convencido de que ele era poderoso para cumprir o que havia prometido.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28045, 22, "Em conseqüência, ""isso lhe foi também creditado como justiça"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28046, 23, "As palavras ""lhe foi creditado"" não foram escritas apenas para ele,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28047, 24, "mas também para nós, a quem Deus creditará justiça, para nós, que cremos naquele que ressuscitou dos mortos a Jesus, nosso Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28048, 25, "Ele foi entregue à morte por nossos pecados e ressuscitado para nossa justificação.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28049, 1, "Tendo sido, pois, justificados pela fé, temos paz com Deus, por nosso Senhor Jesus Cristo,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28050, 2, "por meio de quem obtivemos acesso pela fé a esta graça na qual agora estamos firmes; e nos gloriamos na esperança da glória de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28051, 3, "Não só isso, mas também nos gloriamos nas tribulações, porque sabemos que a tribulação produz perseverança;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28052, 4, "a perseverança, um caráter aprovado; e o caráter aprovado, esperança.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28053, 5, "E a esperança não nos decepciona, porque Deus derramou seu amor em nossos corações, por meio do Espírito Santo que ele nos concedeu.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28054, 6, "De fato, no devido tempo, quando ainda éramos fracos, Cristo morreu pelos ímpios.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28055, 7, "Dificilmente haverá alguém que morra por um justo; pelo homem bom talvez alguém tenha coragem de morrer.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28056, 8, "Mas Deus demonstra seu amor por nós: Cristo morreu em nosso favor quando ainda éramos pecadores.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28057, 9, "Como agora fomos justificados por seu sangue, muito mais ainda seremos salvos da ira de Deus por meio dele!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28058, 10, "Se quando éramos inimigos de Deus fomos reconciliados com ele mediante a morte de seu Filho, quanto mais agora, tendo sido reconciliados, seremos salvos por sua vida!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28059, 11, "Não apenas isso, mas também nos gloriamos em Deus, por meio de nosso Senhor Jesus Cristo, mediante quem recebemos agora a reconciliação.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28060, 12, "Portanto, da mesma forma como o pecado entrou no mundo por um homem, e pelo pecado a morte, assim também a morte veio a todos os homens, porque todos pecaram;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28061, 13, "pois antes de ser dada a lei, o pecado já estava no mundo. Mas o pecado não é levado em conta quando não existe lei.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28062, 14, "Todavia, a morte reinou desde o tempo de Adão até o de Moisés, mesmo sobre aqueles que não cometeram pecado semelhante à transgressão de Adão, o qual era um tipo daquele que haveria de vir.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28063, 15, "Entretanto, não há comparação entre a dádiva e a transgressão. Pois se muitos morreram por causa da transgressão de um só, muito mais a graça de Deus, isto é, a dádiva pela graça de um só homem, Jesus Cristo, transbordou para muitos!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28064, 16, "Não se pode comparar a dádiva de Deus com a conseqüência do pecado de um só homem: por um pecado veio o julgamento que trouxe condenação, mas a dádiva decorreu de muitas transgressões e trouxe justificação.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28065, 17, "Se pela transgressão de um só a morte reinou por meio dele, muito mais aqueles que recebem de Deus a imensa provisão da graça e a dádiva da justiça reinarão em vida por meio de um único homem, Jesus Cristo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28066, 18, "Conseqüentemente, assim como uma só transgressão resultou na condenação de todos os homens, assim também um só ato de justiça resultou na justificação que traz vida a todos os homens.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28067, 19, "Logo, assim como por meio da desobediência de um só homem muitos foram feitos pecadores, assim também, por meio da obediência de um único homem muitos serão feitos justos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28068, 20, "A lei foi introduzida para que a transgressão fosse ressaltada. Mas onde aumentou o pecado, transbordou a graça,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28069, 21, "a fim de que, assim como o pecado reinou na morte, também a graça reine pela justiça para conceder vida eterna, mediante Jesus Cristo, nosso Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28070, 1, "Que diremos então? Continuaremos pecando para que a graça aumente?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28071, 2, "De maneira nenhuma! Nós, os que morremos para o pecado, como podemos continuar vivendo nele?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28072, 3, "Ou vocês não sabem que todos nós, que fomos batizados em Cristo Jesus, fomos batizados em sua morte?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28073, 4, "Portanto, fomos sepultados com ele na morte por meio do batismo, a fim de que, assim como Cristo foi ressuscitado dos mortos mediante a glória do Pai, também nós vivamos uma vida nova.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28074, 5, "Se dessa forma fomos unidos a ele na semelhança da sua morte, certamente o seremos também na semelhança da sua ressurreição.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28075, 6, "Pois sabemos que o nosso velho homem foi crucificado com ele, para que o corpo do pecado seja destruído, e não mais sejamos escravos do pecado;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28076, 7, "pois quem morreu, foi justificado do pecado.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28077, 8, "Ora, se morremos com Cristo, cremos que também com ele viveremos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28078, 9, "Pois sabemos que, tendo sido ressuscitado dos mortos, Cristo não pode morrer outra vez: a morte não tem mais domínio sobre ele.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28079, 10, "Porque morrendo, ele morreu para o pecado uma vez por todas; mas vivendo, vive para Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28080, 11, "Da mesma forma, considerem-se mortos para o pecado, mas vivos para Deus em Cristo Jesus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28081, 12, "Portanto, não permitam que o pecado continue dominando os seus corpos mortais, fazendo que vocês obedeçam aos seus desejos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28082, 13, "Não ofereçam os membros dos seus corpos ao pecado, como instrumentos de injustiça; antes ofereçam-se a Deus como quem voltou da morte para a vida; e ofereçam os membros dos seus corpos a ele, como instrumentos de justiça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28083, 14, "Pois o pecado não os dominará, porque vocês não estão debaixo da lei, mas debaixo da graça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28084, 15, "E então? Vamos pecar porque não estamos debaixo da lei, mas debaixo da graça? De maneira nenhuma!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28085, 16, "Não sabem que, quando vocês se oferecem a alguém para lhe obedecer como escravos, tornam-se escravos daquele a quem obedecem: escravos do pecado que leva à morte, ou da obediência que leva à justiça?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28086, 17, "Mas, graças a Deus, porque, embora vocês tenham sido escravos do pecado, passaram a obedecer de coração à forma de ensino que lhes foi transmitida.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28087, 18, "Vocês foram libertados do pecado e tornaram-se escravos da justiça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28088, 19, "Falo isso em termos humanos por causa das suas limitações humanas. Assim como vocês ofereceram os membros dos seus corpos em escravidão à impureza e à maldade que leva à maldade, ofereçam-nos agora em escravidão à justiça que leva à santidade.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28089, 20, "Quando vocês eram escravos do pecado, estavam livres da justiça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28090, 21, "Que fruto colheram então das coisas das quais agora vocês se envergonham? O fim delas é a morte!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28091, 22, "Mas agora que vocês foram libertados do pecado e se tornaram escravos de Deus, o fruto que colhem leva à santidade, e o seu fim é a vida eterna.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28092, 23, "Pois o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28093, 1, "Meus irmãos, falo a vocês como a pessoas que conhecem a lei. Acaso vocês não sabem que a lei tem autoridade sobre alguém apenas enquanto ele vive?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28094, 2, "Por exemplo, pela lei a mulher casada está ligada a seu marido enquanto ele estiver vivo; mas, se o marido morrer, ela estará livre da lei do casamento.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28095, 3, "Por isso, se ela se casar com outro homem enquanto seu marido ainda estiver vivo, será considerada adúltera. Mas se o marido morrer, ela estará livre daquela lei, e mesmo que venha a se casar com outro homem, não será adúltera.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28096, 4, "Assim, meus irmãos, vocês também morreram para a lei, por meio do corpo de Cristo, para pertencerem a outro, àquele que ressuscitou dos mortos, a fim de que venhamos a dar fruto para Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28097, 5, "Pois quando éramos controlados pela carne, as paixões pecaminosas despertadas pela lei atuavam em nossos corpos, de forma que dávamos fruto para a morte.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28098, 6, "Mas agora, morrendo para aquilo que antes nos prendia, fomos libertados da lei, para que sirvamos conforme o novo modo do Espírito, e não segundo a velha forma da lei escrita.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28099, 7, "Que diremos então? A lei é pecado? De maneira nenhuma! De fato, eu não saberia o que é pecado, a não ser por meio da lei. Pois, na realidade, eu não saberia o que é cobiça, se a lei não dissesse: ""Não cobiçarás"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28100, 8, "Mas o pecado, aproveitando a oportunidade dada pelo mandamento, produziu em mim todo tipo de desejo cobiçoso. Pois, sem a lei, o pecado está morto.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28101, 9, "Antes, eu vivia sem a lei, mas quando o mandamento veio, o pecado reviveu, e eu morri.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28102, 10, "Descobri que o próprio mandamento, destinado a produzir vida, na verdade produziu morte.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28103, 11, "Pois o pecado, aproveitando a oportunidade dada pelo mandamento, enganou-me e por meio do mandamento me matou.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28104, 12, "De fato a lei é santa, e o mandamento é santo, justo e bom.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28105, 13, "E então, o que é bom se tornou em morte para mim? De maneira nenhuma! Mas, para que o pecado se mostrasse como pecado, ele produziu morte em mim por meio do que era bom, de modo que por meio do mandamento ele se mostrasse extremamente pecaminoso.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28106, 14, "Sabemos que a lei é espiritual; eu, contudo, não o sou, pois fui vendido como escravo ao pecado.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28107, 15, "Não entendo o que faço. Pois não faço o que desejo, mas o que odeio.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28108, 16, "E, se faço o que não desejo, admito que a lei é boa.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28109, 17, "Neste caso, não sou mais eu quem o faz, mas o pecado que habita em mim.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28110, 18, "Sei que nada de bom habita em mim, isto é, em minha carne. Porque tenho o desejo de fazer o que é bom, mas não consigo realizá-lo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28111, 19, "Pois o que faço não é o bem que desejo, mas o mal que não quero fazer, esse eu continuo fazendo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28112, 20, "Ora, se faço o que não quero, já não sou eu quem o faz, mas o pecado que habita em mim.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28113, 21, "Assim, encontro esta lei que atua em mim: Quando quero fazer o bem, o mal está junto a mim.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28114, 22, "Pois, no íntimo do meu ser tenho prazer na lei de Deus;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28115, 23, "mas vejo outra lei atuando nos membros do meu corpo, guerreando contra a lei da minha mente, tornando-me prisioneiro da lei do pecado que atua em meus membros.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28116, 24, "Miserável homem eu que sou! Quem me libertará do corpo sujeito a esta morte?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28117, 25, "Graças a Deus por Jesus Cristo, nosso Senhor! De modo que, com a mente, eu próprio sou escravo da lei de Deus; mas, com a carne, da lei do pecado.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28118, 1, "Portanto, agora já não há condenação para os que estão em Cristo Jesus,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28119, 2, "porque por meio de Cristo Jesus a lei do Espírito de vida me libertou da lei do pecado e da morte.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28120, 3, "Porque, aquilo que a lei fora incapaz de fazer por estar enfraquecida pela carne, Deus o fez, enviando seu próprio Filho, à semelhança do homem pecador, como oferta pelo pecado. E assim condenou o pecado na carne,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28121, 4, "a fim de que as justas exigências da lei fossem plenamente satisfeitas em nós, que não vivemos segundo a carne, mas segundo o Espírito.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28122, 5, "Quem vive segundo a carne tem a mente voltada para o que a carne deseja; mas quem, de acordo com o Espírito, tem a mente voltada para o que o Espírito deseja.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28123, 6, "A mentalidade da carne é morte, mas a mentalidade do Espírito é vida e paz;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28124, 7, "a mentalidade da carne é inimiga de Deus porque não se submete à lei de Deus, nem pode fazê-lo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28125, 8, "Quem é dominado pela carne não pode agradar a Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28126, 9, "Entretanto, vocês não estão sob o domínio da carne, mas do Espírito, se de fato o Espírito de Deus habita em vocês. E, se alguém não tem o Espírito de Cristo, não pertence a Cristo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28127, 10, "Mas se Cristo está em vocês, o corpo está morto por causa do pecado, mas o espírito está vivo por causa da justiça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28128, 11, "E, se o Espírito daquele que ressuscitou Jesus dentre os mortos habita em vocês, aquele que ressuscitou a Cristo dentre os mortos também dará vida a seus corpos mortais, por meio do seu Espírito, que habita em vocês.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28129, 12, "Portanto, irmãos, estamos em dívida, não para com a carne, para vivermos sujeitos a ela.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28130, 13, "Pois se vocês viverem de acordo com a carne, morrerão; mas, se pelo Espírito fizerem morrer os atos do corpo, viverão,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28131, 14, "porque todos os que são guiados pelo Espírito de Deus são filhos de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28132, 15, "Pois vocês não receberam um espírito que os escravize para novamente temer, mas receberam o Espírito que os adota como filhos, por meio do qual clamamos: ""Aba, Pai"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28133, 16, "O próprio Espírito testemunha ao nosso espírito que somos filhos de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28134, 17, "Se somos filhos, então somos herdeiros; herdeiros de Deus e co-herdeiros com Cristo, se de fato participamos dos seus sofrimentos, para que também participemos da sua glória.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28135, 18, "Considero que os nossos sofrimentos atuais não podem ser comparados com a glória que em nós será revelada.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28136, 19, "A natureza criada aguarda, com grande expectativa, que os filhos de Deus sejam revelados.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28137, 20, "Pois ela foi submetida à futilidade, não pela sua própria escolha, mas por causa da vontade daquele que a sujeitou, na esperança", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28138, 21, "de que a própria natureza criada será libertada da escravidão da decadência em que se encontra para a gloriosa liberdade dos filhos de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28139, 22, "Sabemos que toda a natureza criada geme até agora, como em dores de parto.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28140, 23, "E não só isso, mas nós mesmos, que temos os primeiros frutos do Espírito, gememos interiormente, esperando ansiosamente nossa adoção como filhos, a redenção do nosso corpo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28141, 24, "Pois nessa esperança fomos salvos. Mas, esperança que se vê não é esperança. Quem espera por aquilo que está vendo?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28142, 25, "Mas se esperamos o que ainda não vemos, aguardamo-lo pacientemente.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28143, 26, "Da mesma forma o Espírito nos ajuda em nossa fraqueza, pois não sabemos como orar, mas o próprio Espírito intercede por nós com gemidos inexprimíveis.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28144, 27, "E aquele que sonda os corações conhece a intenção do Espírito, porque o Espírito intercede pelos santos de acordo com a vontade de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28145, 28, "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28146, 29, "Pois aqueles que de antemão conheceu, também os predestinou para serem conformes à imagem de seu Filho, a fim de que ele seja o primogênito entre muitos irmãos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28147, 30, "E aos que predestinou, também chamou; aos que chamou, também justificou; aos que justificou, também glorificou.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28148, 31, "Que diremos, pois, diante dessas coisas? Se Deus é por nós, quem será contra nós?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28149, 32, "Aquele que não poupou a seu próprio Filho, mas o entregou por todos nós, como não nos dará juntamente com ele, e de graça, todas as coisas?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28150, 33, "Quem fará alguma acusação contra os escolhidos de Deus? É Deus quem os justifica.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28151, 34, "Quem os condenará? Foi Cristo Jesus que morreu; e mais, que ressuscitou e está à direita de Deus, e também intercede por nós.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28152, 35, "Quem nos separará do amor de Cristo? Será tribulação, ou angústia, ou perseguição, ou fome, ou nudez, ou perigo, ou espada?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28153, 36, "Como está escrito: ""Por amor de ti enfrentamos a morte todos os dias; somos considerados como ovelhas destinadas ao matadouro"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28154, 37, "Mas, em todas estas coisas somos mais que vencedores, por meio daquele que nos amou.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28155, 38, "Pois estou convencido de que nem morte nem vida, nem anjos nem demônios, nem o presente nem o futuro, nem quaisquer poderes,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28156, 39, "nem altura nem profundidade, nem qualquer outra coisa na criação será capaz de nos separar do amor de Deus que está em Cristo Jesus, nosso Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28157, 1, "Digo a verdade em Cristo, não minto; minha consciência o confirma no Espírito Santo:", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28158, 2, "tenho grande tristeza e constante angústia em meu coração.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28159, 3, "Pois eu até desejaria ser amaldiçoado e separado de Cristo por amor de meus irmãos, os de minha raça,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28160, 4, "o povo de Israel. Deles é a adoção de filhos; deles é a glória divina, as alianças, a concessão da lei, a adoração no templo e as promessas.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28161, 5, "Deles são os patriarcas, e a partir deles se traça a linhagem humana de Cristo, que é Deus acima de tudo, bendito para sempre! Amém.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28162, 6, "Não pensemos que a palavra de Deus falhou. Pois nem todos os descendentes de Israel são Israel.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28163, 7, "Nem por serem descendentes de Abraão passaram todos a ser filhos de Abraão. Pelo contrário: ""Por meio de Isaque a sua descendência será considerada"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28164, 8, "Noutras palavras, não são os filhos naturais que são filhos de Deus, mas os filhos da promessa é que são considerados descendência de Abraão.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28165, 9, "Pois foi assim que a promessa foi feita: ""no tempo devido virei novamente, e Sara terá um filho"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28166, 10, "E esse não foi o único caso; também os filhos de Rebeca tiveram um mesmo pai, nosso pai Isaque.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28167, 11, "Todavia, antes que os gêmeos nascessem ou fizessem qualquer coisa boa ou má — a fim de que o propósito de Deus conforme a eleição permanecesse,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28168, 12, "não por obras, mas por aquele que chama — foi dito a ela: ""O mais velho servirá ao mais novo"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28169, 13, "Como está escrito: ""Amei Jacó, mas rejeitei Esaú"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28170, 14, "E então, que diremos? Acaso Deus é injusto? De maneira nenhuma!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28171, 15, "Pois ele diz a Moisés: ""Terei misericórdia de quem eu quiser ter misericórdia e terei compaixão de quem eu quiser ter compaixão"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28172, 16, "Portanto, isso não depende do desejo ou do esforço humano, mas da misericórdia de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28173, 17, "Pois a Escritura diz ao faraó: ""Eu o levantei exatamente com este propósito: mostrar em você o meu poder, e para que o meu nome seja proclamado em toda a terra"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28174, 18, "Portanto, Deus tem misericórdia de quem ele quer, e endurece a quem ele quer.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28175, 19, "Mas algum de vocês me dirá: ""Então, por que Deus ainda nos culpa? Pois, quem resiste à sua vontade? """, 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28176, 20, "Mas quem é você, ó homem, para questionar a Deus? ""Acaso aquilo que é formado pode dizer ao que o formou: ‘Por que me fizeste assim? ’ """, 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28177, 21, "O oleiro não tem direito de fazer do mesmo barro um vaso para fins nobres e outro para uso desonroso?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28178, 22, "E se Deus, querendo mostrar a sua ira e tornar conhecido o seu poder, suportou com grande paciência os vasos de sua ira, preparados para destruição?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28179, 23, "Que dizer, se ele fez isto para tornar conhecidas as riquezas de sua glória aos vasos de sua misericórdia, que preparou de antemão para glória,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28180, 24, "ou seja, a nós, a quem também chamou, não apenas dentre os judeus, mas também dentre os gentios?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28181, 25, "Como ele diz em Oséias: ""Chamarei ‘meu povo’ a quem não é meu povo; e chamarei ‘minha amada’ a quem não é minha amada"",", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28182, 26, "e: ""Acontecerá que, no mesmo lugar em que se lhes declarou: ‘Vocês não são meu povo’, eles serão chamados ‘filhos do Deus vivo’. """, 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28183, 27, "Isaías exclama com relação a Israel: ""Embora o número dos israelitas seja como a areia do mar, apenas o remanescente será salvo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28184, 28, "Pois o Senhor executará na terra a sua sentença, rápida e definitivamente"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28185, 29, "Como anteriormente disse Isaías: ""Se o Senhor dos Exércitos não nos tivesse deixado descendentes, já estaríamos como Sodoma, e semelhantes a Gomorra"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28186, 30, "Que diremos, então? Os gentios, que não buscavam justiça, a obtiveram, uma justiça que vem da fé;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28187, 31, "mas Israel, que buscava uma lei que trouxesse justiça, não a alcançou.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28188, 32, "Por que não? Porque não a buscava pela fé, mas como se fosse por obras. Eles tropeçaram na ""pedra de tropeço"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28189, 33, "Como está escrito: ""Eis que ponho em Sião uma pedra de tropeço e uma rocha que faz cair; e aquele que nela confia jamais será envergonhado"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28190, 1, "Irmãos, o desejo do meu coração e a minha oração a Deus pelos israelitas é que eles sejam salvos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28191, 2, "Pois posso testemunhar que eles têm zelo por Deus, mas o seu zelo não se baseia no conhecimento.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28192, 3, "Porquanto, ignorando a justiça que vem de Deus e procurando estabelecer a sua própria, não se submeteram à justiça de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28193, 4, "Porque o fim da lei é Cristo, para a justificação de todo o que crê.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28194, 5, "Moisés descreve desta forma a justiça que vem da lei: ""O homem que fizer estas coisas viverá por meio delas"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28195, 6, "Mas a justiça que vem da fé diz: ""Não diga em seu coração: ‘Quem subirá ao céu? ’ ( isto é, para fazer Cristo descer )", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28196, 7, "ou ‘Quem descerá ao abismo? ’ "" ( isto é, para fazer subir Cristo dentre os mortos ).", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28197, 8, "Mas o que ela diz? ""A palavra está perto de você; está em sua boca e em seu coração"", isto é, a palavra da fé que estamos proclamando:", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28198, 9, "Se você confessar com a sua boca que Jesus é Senhor e crer em seu coração que Deus o ressuscitou dentre os mortos, será salvo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28199, 10, "Pois com o coração se crê para justiça, e com a boca se confessa para salvação.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28200, 11, "Como diz a Escritura: ""Todo o que nele confia jamais será envergonhado"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28201, 12, "Não há diferença entre judeus e gentios, pois o mesmo Senhor é Senhor de todos e abençoa ricamente todos os que o invocam,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28202, 13, "porque ""todo aquele que invocar o nome do Senhor será salvo"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28203, 14, "Como, pois, invocarão aquele em quem não creram? E como crerão naquele de quem não ouviram falar? E como ouvirão, se não houver quem pregue?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28204, 15, "E como pregarão, se não forem enviados? Como está escrito: ""Como são belos os pés dos que anunciam boas novas! """, 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28205, 16, "No entanto, nem todos os israelitas aceitaram as boas novas. Pois Isaías diz: ""Senhor, quem creu em nossa mensagem? """, 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28206, 17, "Conseqüentemente, a fé vem por ouvir a mensagem, e a mensagem é ouvida mediante a palavra de Cristo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28207, 18, "Mas eu pergunto: Eles não a ouviram? Claro que sim: ""A sua voz ressoou por toda a terra, e as suas palavras, até os confins do mundo"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28208, 19, "Novamente pergunto: Será que Israel não entendeu? Moisés foi o primeiro que disse: ""Farei que tenham ciúmes de quem não é meu povo; eu os provocarei à ira por meio de um povo sem entendimento"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28209, 20, "E Isaías diz ousadamente: ""Fui achado por aqueles que não me procuravam; revelei-me àqueles que não perguntavam por mim"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28210, 21, "Mas a respeito de Israel, ele diz: ""O tempo todo estendi as mãos a um povo desobediente e rebelde"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28211, 1, "Pergunto, pois: Acaso Deus rejeitou o seu povo? De maneira nenhuma! Eu mesmo sou israelita, descendente de Abraão, da tribo de Benjamim.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28212, 2, "Deus não rejeitou o seu povo, o qual de antemão conheceu. Ou vocês não sabem como Elias clamou a Deus contra Israel, conforme diz a Escritura?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28213, 3, """Senhor, mataram os teus profetas e derrubaram os teus altares; sou o único que sobrou, e agora estão procurando matar-me"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28214, 4, "E qual foi a resposta divina? ""Reservei para mim sete mil homens que não dobraram os joelhos diante de Baal"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28215, 5, "Assim, hoje também há um remanescente escolhido pela graça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28216, 6, "E, se é pela graça, já não é mais pelas obras; se fosse, a graça já não seria graça.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28217, 7, "Que dizer então? Israel não conseguiu aquilo que tanto buscava, mas os eleitos o obtiveram. Os demais foram endurecidos,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28218, 8, "como está escrito: ""Deus lhes deu um espírito de atordoamento, olhos para não ver e ouvidos para não ouvir, até o dia de hoje"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28219, 9, "E Davi diz: ""Que a mesa deles se transforme em laço e armadilha, pedra de tropeço e retribuição para eles.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28220, 10, "Escurençam-se os seus olhos, para que não consigam ver, e suas costas fiquem encurvadas para sempre"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28221, 11, "Novamente pergunto: Acaso tropeçaram para que ficassem caídos? De maneira nenhuma! Ao contrário, por causa da transgressão deles, veio salvação para os gentios, para provocar ciúme em Israel.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28222, 12, "Mas se a transgressão deles significa riqueza para o mundo, e o seu fracasso, riqueza para os gentios, quanto mais significará a sua plenitude!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28223, 13, "Estou falando a vocês, gentios. Visto que sou apóstolo para os gentios, exalto o meu ministério,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28224, 14, "na esperança de que de alguma forma possa provocar ciúme em meu próprio povo e salvar alguns deles.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28225, 15, "Pois se a rejeição deles é a reconciliação do mundo, o que será a sua aceitação, senão vida dentre os mortos?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28226, 16, "Se é santa a parte da massa que é oferecida como primeiros frutos, toda a massa também o é; se a raiz é santa, os ramos também o serão.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28227, 17, "Se alguns ramos foram cortados, e você, sendo oliveira brava, foi enxertado entre os outros e agora participa da seiva que vem da raiz da oliveira,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28228, 18, "não se glorie contra esses ramos. Se o fizer, saiba que não é você quem sustenta a raiz, mas a raiz a você.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28229, 19, "Então você dirá: ""Os ramos foram cortados, para que eu fosse enxertado"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28230, 20, "Está certo. Eles, porém, foram cortados devido à incredulidade, e você permanece pela fé. Não se orgulhe, mas tema.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28231, 21, "Pois se Deus não poupou os ramos naturais, também não poupará você.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28232, 22, "Portanto, considere a bondade e a severidade de Deus: severidade para com aqueles que caíram, mas bondade para com você, desde que permaneça na bondade dele. De outra forma, você também será cortado.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28233, 23, "E quanto a eles, se não continuarem na incredulidade, serão enxertados, pois Deus é capaz de enxertá-los outra vez.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28234, 24, "Afinal de contas, se você foi cortado de uma oliveira brava por natureza e, de maneira antinatural, foi enxertado numa oliveira cultivada, quanto mais serão enxertados os ramos naturais em sua própria oliveira?", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28235, 25, "Irmãos, não quero que ignorem este mistério, para que não se tornem presunçosos: Israel experimentou um endurecimento em parte, até que chegasse a plenitude dos gentios.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28236, 26, "E assim todo o Israel será salvo, como está escrito: ""Virá de Sião o redentor que desviará de Jacó a impiedade.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28237, 27, "E esta é a minha aliança com eles quando eu remover os seus pecados"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28238, 28, "Quanto ao evangelho, eles são inimigos por causa de vocês; mas quanto à eleição, são amados por causa dos patriarcas,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28239, 29, "pois os dons e o chamado de Deus são irrevogáveis.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28240, 30, "Assim como vocês, que antes eram desobedientes a Deus mas agora receberam misericórdia, graças à desobediência deles,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28241, 31, "assim também agora eles se tornaram desobedientes, a fim de que também recebam agora misericórdia, graças à misericórdia de Deus para com vocês.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28242, 32, "Pois Deus colocou todos sob a desobediência, para exercer misericórdia para com todos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28243, 33, "Ó profundidade da riqueza da sabedoria e do conhecimento de Deus! Quão insondáveis são os seus juízos, e inescrutáveis os seus caminhos!", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28244, 34, """Quem conheceu a mente do Senhor? Ou quem foi seu conselheiro? """, 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28245, 35, """Quem primeiro lhe deu, para que ele o recompense? """, 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28246, 36, "Pois dele, por ele e para ele são todas as coisas. A ele seja a glória para sempre! Amém.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28247, 1, "Portanto, irmãos, rogo-lhes pelas misericórdias de Deus que se ofereçam em sacrifício vivo, santo e agradável a Deus; este é o culto racional de vocês.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28248, 2, "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28249, 3, "Pois pela graça que me foi dada digo a todos vocês: ninguém tenha de si mesmo um conceito mais elevado do que deve ter; mas, pelo contrário, tenha um conceito equilibrado, de acordo com a medida da fé que Deus lhe concedeu.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28250, 4, "Assim como cada um de nós tem um corpo com muitos membros e esses membros não exercem todos a mesma função,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28251, 5, "assim também em Cristo nós, que somos muitos, formamos um corpo, e cada membro está ligado a todos os outros.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28252, 6, "Temos diferentes dons, de acordo com a graça que nos foi dada. Se alguém tem o dom de profetizar, use-o na proporção da sua fé.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28253, 7, "Se o seu dom é servir, sirva; se é ensinar, ensine;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28254, 8, "se é dar ânimo, que assim faça; se é contribuir, que contribua generosamente; se é exercer liderança, que a exerça com zelo; se é mostrar misericórdia, que o faça com alegria.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28255, 9, "O amor deve ser sincero. Odeiem o que é mau; apeguem-se ao que é bom.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28256, 10, "Dediquem-se uns aos outros com amor fraternal. Prefiram dar honra aos outros mais do que a si próprios.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28257, 11, "Nunca lhes falte o zelo, sejam fervorosos no espírito, sirvam ao Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28258, 12, "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28259, 13, "Compartilhem o que vocês têm com os santos em suas necessidades. Pratiquem a hospitalidade.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28260, 14, "Abençoem aqueles que os perseguem; abençoem, e não os amaldiçoem.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28261, 15, "Alegrem-se com os que se alegram; chorem com os que choram.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28262, 16, "Tenham uma mesma atitude uns para com os outros. Não sejam orgulhosos, mas estejam dispostos a associar-se a pessoas de posição inferior. Não sejam sábios aos seus próprios olhos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28263, 17, "Não retribuam a ninguém mal por mal. Procurem fazer o que é correto aos olhos de todos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28264, 18, "Façam todo o possível para viver em paz com todos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28265, 19, "Amados, nunca procurem vingar-se, mas deixem com Deus a ira, pois está escrito: ""Minha é a vingança; eu retribuirei"", diz o Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28266, 20, "Pelo contrário: ""Se o seu inimigo tiver fome, dê-lhe de comer; se tiver sede, dê-lhe de beber. Fazendo isso, você amontoará brasas vivas sobre a cabeça dele"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28267, 21, "Não se deixem vencer pelo mal, mas vençam o mal com o bem.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28268, 1, "Todos devem sujeitar-se às autoridades governamentais, pois não há autoridade que não venha de Deus; as autoridades que existem foram por ele estabelecidas.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28269, 2, "Portanto, aquele que se rebela contra a autoridade está se colocando contra o que Deus instituiu, e aqueles que assim procedem trazem condenação sobre si mesmos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28270, 3, "Pois os governantes não devem ser temidos, a não ser pelos que praticam o mal. Você quer viver livre do medo da autoridade? Pratique o bem, e ela o enaltecerá.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28271, 4, "Pois é serva de Deus para o seu bem. Mas se você praticar o mal, tenha medo, pois ela não porta a espada sem motivo. É serva de Deus, agente da justiça para punir quem pratica o mal.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28272, 5, "Portanto, é necessário que sejamos submissos às autoridades, não apenas por causa da possibilidade de uma punição, mas também por questão de consciência.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28273, 6, "É por isso também que vocês pagam imposto, pois as autoridades estão a serviço de Deus, sempre dedicadas a esse trabalho.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28274, 7, "Dêem a cada um o que lhe é devido: Se imposto, imposto; se tributo, tributo; se temor, temor; se honra, honra.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28275, 8, "Não devam nada a ninguém, a não ser o amor de uns pelos outros, pois aquele que ama seu próximo tem cumprido a lei.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28276, 9, "Pois estes mandamentos: ""Não adulterarás"", ""não matarás"", ""não furtarás"", ""não cobiçarás"", e qualquer outro mandamento, todos se resumem neste preceito: ""Ame o seu próximo como a si mesmo"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28277, 10, "O amor não pratica o mal contra o próximo. Portanto, o amor é o cumprimento da lei.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28278, 11, "Façam isso, compreendendo o tempo em que vivemos. Chegou a hora de vocês despertarem do sono, porque agora a nossa salvação está mais próxima do que quando cremos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28279, 12, "A noite está quase acabando; o dia logo vem. Portanto, deixemos de lado as obras das trevas e vistamo-nos a armadura da luz.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28280, 13, "Comportemo-nos com decência, como quem age à luz do dia, não em orgias e bebedeiras, não em imoralidade sexual e depravação, não em desavença e inveja.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28281, 14, "Pelo contrário, revistam-se do Senhor Jesus Cristo, e não fiquem premeditando como satisfazer os desejos da carne.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28282, 1, "Aceitem o que é fraco na fé, sem discutir assuntos controvertidos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28283, 2, "Um crê que pode comer de tudo; já outro, cuja fé é fraca, come apenas alimentos vegetais.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28284, 3, "Aquele que come de tudo não deve desprezar o que não come, e aquele que não come de tudo não deve condenar aquele que come, pois Deus o aceitou.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28285, 4, "Quem é você para julgar o servo alheio? É para o seu senhor que ele está de pé ou cai. E ficará de pé, pois o Senhor é capaz de o sustentar.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28286, 5, "Há quem considere um dia mais sagrado que outro; há quem considere iguais todos os dias. Cada um deve estar plenamente convicto em sua própria mente.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28287, 6, "Aquele que considera um dia como especial, para o Senhor assim o faz. Aquele que come carne, come para o Senhor, pois dá graças a Deus; e aquele que se abstém, para o Senhor se abstém, e dá graças a Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28288, 7, "Pois nenhum de nós vive apenas para si, e nenhum de nós morre apenas para si.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28289, 8, "Se vivemos, vivemos para o Senhor; e, se morremos, morremos para o Senhor. Assim, quer vivamos, quer morramos, pertencemos ao Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28290, 9, "Por esta razão Cristo morreu e voltou a viver, para ser Senhor de vivos e de mortos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28291, 10, "Portanto, você, por que julga seu irmão? E por que despreza seu irmão? Pois todos compareceremos diante do tribunal de Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28292, 11, "Porque está escrito: "" ‘Por mim mesmo jurei’, diz o Senhor, ‘diante de mim todo joelho se dobrará e toda língua confessará que sou Deus’ "".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28293, 12, "Assim, cada um de nós prestará contas de si mesmo a Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28294, 13, "Portanto, deixemos de julgar uns aos outros. Em vez disso, façamos o propósito de não colocar pedra de tropeço ou obstáculo no caminho do irmão.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28295, 14, "Como alguém que está no Senhor Jesus, tenho plena convicção de que nenhum alimento é por si mesmo impuro, a não ser para quem assim o considere; para ele é impuro.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28296, 15, "Se o seu irmão se entristece devido ao que você come, você já não está agindo por amor. Por causa da sua comida, não destrua seu irmão, por quem Cristo morreu.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28297, 16, "Aquilo que é bom para vocês não se torne objeto de maledicência.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28298, 17, "Pois o Reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo;", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28299, 18, "aquele que assim serve a Cristo é agradável a Deus e aprovado pelos homens.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28300, 19, "Por isso, esforcemo-nos em promover tudo quanto conduz à paz e à edificação mútua.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28301, 20, "Não destrua a obra de Deus por causa da comida. Todo alimento é puro, mas é errado comer qualquer coisa que faça os outros tropeçarem.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28302, 21, "É melhor não comer carne nem beber vinho, nem fazer qualquer outra coisa que leve seu irmão a cair.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28303, 22, "Assim, seja qual for o seu modo de crer a respeito destas coisas, que isso permaneça entre você e Deus. Feliz é o homem que não se condena naquilo que aprova.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28304, 23, "Mas aquele que tem dúvida é condenado se comer, porque não come com fé; e tudo o que não provém da fé é pecado.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28305, 1, "Nós, que somos fortes, devemos suportar as fraquezas dos fracos, e não agradar a nós mesmos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28306, 2, "Cada um de nós deve agradar ao seu próximo para o bem dele, a fim de edificá-lo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28307, 3, "Pois também Cristo não agradou a si próprio, mas, como está escrito: ""Os insultos daqueles que te insultam caíram sobre mim"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28308, 4, "Pois tudo o que foi escrito no passado, foi escrito para nos ensinar, de forma que, por meio da perseverança e do bom ânimo procedentes das Escrituras, mantenhamos a nossa esperança.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28309, 5, "O Deus que concede perseverança e ânimo dê-lhes um espírito de unidade, segundo Cristo Jesus,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28310, 6, "para que com um só coração e uma só boca vocês glorifiquem ao Deus e Pai de nosso Senhor Jesus Cristo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28311, 7, "Portanto, aceitem-se uns aos outros, da mesma forma como Cristo os aceitou, a fim de que vocês glorifiquem a Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28312, 8, "Pois eu lhes digo que Cristo se tornou servo dos que são da circuncisão, por amor à verdade de Deus, para confirmar as promessas feitas aos patriarcas,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28313, 9, "a fim de que os gentios glorifiquem a Deus por sua misericórdia, como está escrito: ""Por isso, eu te louvarei entre os gentios; Cantarei louvores ao teu nome"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28314, 10, "E também diz: ""Cantem de alegria, ó gentios, com o povo dele"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28315, 11, "E mais: ""Louvem o Senhor, todos vocês, gentios; cantem louvores a ele todos os povos"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28316, 12, "E Isaías também diz: ""Brotará a raiz de Jessé, aquele que se levantará para reinar sobre os gentios; estes colocarão nele a sua esperança"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28317, 13, "Que o Deus da esperança os encha de toda alegria e paz, por sua confiança nele, para que vocês transbordem de esperança, pelo poder do Espírito Santo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28318, 14, "Meus irmãos, eu mesmo estou convencido de que vocês estão cheios de bondade e plenamente instruídos, sendo capazes de aconselhar-se uns aos outros.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28319, 15, "A respeito de alguns assuntos, eu lhes escrevi com toda a franqueza, como para fazê-los lembrar-se novamente deles, por causa da graça que Deus me deu,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28320, 16, "de ser um ministro de Cristo Jesus para os gentios, com o dever sacerdotal de proclamar o evangelho de Deus, para que os gentios se tornem uma oferta aceitável a Deus, santificados pelo Espírito Santo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28321, 17, "Portanto, eu me glorio em Cristo Jesus, em meu serviço a Deus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28322, 18, "Não me atrevo a falar de nada, exceto daquilo que Cristo realizou por meu intermédio em palavra e em ação, a fim de levar os gentios a obedecerem a Deus:", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28323, 19, "pelo poder de sinais e maravilhas e por meio do poder do Espírito de Deus. Assim, desde Jerusalém e arredores, até o Ilírico, proclamei plenamente o evangelho de Cristo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28324, 20, "Sempre fiz questão de pregar o evangelho onde Cristo ainda não era conhecido, de forma que não estivesse edificando sobre alicerce de outro.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28325, 21, "Mas antes, como está escrito: ""Hão de vê-lo aqueles que não tinham ouvido falar dele, e o entenderão aqueles que não o haviam escutado"".", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28326, 22, "É por isso que muitas vezes fui impedido de chegar até vocês.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28327, 23, "Mas agora, não havendo nestas regiões nenhum lugar em que precise trabalhar, e visto que há muitos anos anseio vê-los,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28328, 24, "planejo fazê-lo quando for à Espanha. Espero visitá-los de passagem e dar-lhes a oportunidade de me ajudar em minha viagem para lá, depois de ter desfrutado um pouco da companhia de vocês.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28329, 25, "Agora, porém, estou de partida para Jerusalém, a serviço dos santos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28330, 26, "Pois a Macedônia e a Acaia tiveram a alegria de contribuir para os pobres dentre os santos de Jerusalém.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28331, 27, "Eles tiveram prazer nisso, e de fato são devedores a eles. Pois se os gentios participaram das bênçãos espirituais dos judeus, devem também servir aos judeus com seus bens materiais.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28332, 28, "Assim, depois de completar essa tarefa e de ter a certeza de que eles receberam esse fruto, irei à Espanha e visitarei vocês de passagem.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28333, 29, "Sei que, quando for visitá-los, irei na plenitude da bênção de Cristo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28334, 30, "Recomendo-lhes, irmãos, por nosso Senhor Jesus Cristo e pelo amor do Espírito, que se unam a mim em minha luta, orando a Deus em meu favor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28335, 31, "Orem para que eu esteja livre dos descrentes da Judéia e que o meu serviço em Jerusalém seja aceitável aos santos,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28336, 32, "de forma que, pela vontade de Deus, eu os visite com alegria e juntamente com vocês desfrute de um período de refrigério.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28337, 33, "O Deus da paz seja com todos vocês. Amém.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28338, 1, "Recomendo-lhes nossa irmã Febe, serva da igreja em Cencréia.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28339, 2, "Peço que a recebam no Senhor, de maneira digna dos santos, e lhe prestem a ajuda de que venha a necessitar; pois tem sido de grande auxílio para muita gente, inclusive para mim.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28340, 3, "Saúdem Priscila e Áqüila, meus colaboradores em Cristo Jesus.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28341, 4, "Arriscaram a vida por mim. Sou grato a eles; não apenas eu, mas todas as igrejas dos gentios.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28342, 5, "Saúdem também a igreja que se reúne na casa deles. Saúdem meu amado irmão Epêneto, que foi o primeiro convertido a Cristo na província da Ásia.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28343, 6, "Saúdem Maria, que trabalhou arduamente por vocês.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28344, 7, "Saúdem Andrônico e Júnias, meus parentes que estiveram na prisão comigo. São notáveis entre os apóstolos, e estavam em Cristo antes de mim.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28345, 8, "Saúdem Amplíato, meu amado irmão no Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28346, 9, "Saúdem Urbano, nosso cooperador em Cristo, e meu amado irmão Estáquis.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28347, 10, "Saúdem Apeles, aprovado em Cristo. Saúdem os que pertencem à casa de Aristóbulo.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28348, 11, "Saúdem Herodião, meu parente. Saúdem os da casa de Narciso, que estão no Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28349, 12, "Saúdem Trifena e Trifosa, mulheres que trabalham arduamente no Senhor. Saúdem a amada Pérside, outra que trabalhou arduamente no Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28350, 13, "Saúdem Rufo, eleito no Senhor, e sua mãe, que tem sido mãe também para mim.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28351, 14, "Saúdem Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e os irmãos que estão com eles.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28352, 15, "Saúdem Filólogo, Júlia, Nereu e sua irmã, e também Olimpas e todos os santos que estão com eles.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28353, 16, "Saúdem uns aos outros com beijo santo. Todas as igrejas de Cristo enviam-lhes saudações.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28354, 17, "Recomendo-lhes, irmãos, que tomem cuidado com aqueles que causam divisões e colocam obstáculos ao ensino que vocês têm recebido. Afastem-se deles.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28355, 18, "Pois essas pessoas não estão servindo a Cristo, nosso Senhor, mas a seus próprios apetites. Mediante palavras suaves e bajulação, enganam os corações dos ingênuos.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28356, 19, "Todos têm ouvido falar da obediência de vocês, por isso estou muito alegre; mas quero que sejam sábios em relação ao que é bom, e sem malícia em relação ao que é mau.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28357, 20, "Em breve o Deus da paz esmagará Satanás debaixo dos pés de vocês. A graça de nosso Senhor Jesus seja com vocês.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28358, 21, "Timóteo, meu cooperador, envia-lhes saudações, bem como Lúcio, Jasom e Sosípatro, meus parentes.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28359, 22, "Eu, Tércio, que redigi esta carta, saúdo vocês no Senhor.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28360, 23, "Gaio, cuja hospitalidade eu e toda a igreja desfrutamos, envia-lhes saudações. Erasto, administrador da cidade, e nosso irmão Quarto enviam-lhes saudações.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28361, 24, "Que a graça de nosso Senhor Jesus Cristo seja com vocês todos. Amém.", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28362, 25, "Ora, àquele que tem poder para confirmá-los pelo meu evangelho e pela proclamação de Jesus Cristo, de acordo com a revelação do mistério oculto nos tempos passados,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28363, 26, "mas agora revelado e dado a conhecer pelas Escrituras proféticas por ordem do Deus eterno, para que todas as nações venham a crer nele e a obedecer-lhe,", 44);
INSERT INTO verses (id, number, text, chapter_id) VALUES (28364, 27, "ao único Deus sábio seja dada glória para todo o sempre, por meio de Jesus Cristo. Amém.", 44);